import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import crypto from "node:crypto";
function admin(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase serveur non configuré.");return createClient(u,k,{auth:{autoRefreshToken:false,persistSession:false}});}
async function auth(req:NextRequest){const t=req.headers.get("authorization")?.replace(/^Bearer\\s+/i,"");if(!t)return null;const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)throw new Error("Supabase client non configuré.");const sb=createClient(u,k,{auth:{autoRefreshToken:false,persistSession:false}});return (await sb.auth.getUser(t)).data.user||null;}
async function user(sb:any,au:any){const r=await sb.from("User").select("*").eq("authUserId",au.id).maybeSingle();if(r.error)throw new Error(r.error.message);if(r.data)return r.data;const x=await sb.from("User").insert({id:crypto.randomUUID(),authUserId:au.id,email:au.email??null,updatedAt:new Date().toISOString()}).select("*").single();if(x.error)throw new Error(x.error.message);return x.data;}
async function plan(sb:any,id:string){const r=await sb.from("Subscription").select("plan,updatedAt").eq("userId",id).eq("status","ACTIVE").order("updatedAt",{ascending:false}).limit(1).maybeSingle();const p=String(r.data?.plan||"FREE").toUpperCase();return p==="PRO"?"PRO":p.indexOf("PREMIUM")===0?"PREMIUM":"FREE";}
export async function GET(req:NextRequest){try{const au=await auth(req);if(!au)return NextResponse.json({message:"Session requise."},{status:401});const sb=admin(),u=await user(sb,au),p=await plan(sb,u.id),pr=await sb.from("Profile").select("publicDiscoverable").eq("userId",u.id).maybeSingle();if(pr.error)throw new Error(pr.error.message);return NextResponse.json({plan:p,publicDiscoverable:pr.data?.publicDiscoverable===true,actionImages:Array.isArray(u.actionImages)?u.actionImages:[],portfolioBusiness:u.portfolioBusiness||{text:"",url:""},executiveSummary:u.executiveSummary||"",advertisingVideoUrl:u.advertisingVideoUrl||null,pitchVideoUrl:u.pitchVideoUrl||null,pitchVideoDurationMs:u.pitchVideoDurationMs||null});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Impossible de charger la vitrine."},{status:500});}}
export async function PUT(req:NextRequest){try{const au=await auth(req);if(!au)return NextResponse.json({message:"Session requise."},{status:401});const sb=admin(),u=await user(sb,au),b=await req.json(),update:any={updatedAt:new Date().toISOString()};if(Array.isArray(b.actionImages))update.actionImages=b.actionImages.filter((x:any)=>typeof x==="string").slice(0,6);if(b.portfolioBusiness&&typeof b.portfolioBusiness==="object")update.portfolioBusiness={text:String(b.portfolioBusiness.text||"").slice(0,5000),url:String(b.portfolioBusiness.url||"").slice(0,500)};if(typeof b.executiveSummary==="string")update.executiveSummary=b.executiveSummary.trim().slice(0,3000)||null;const x=await sb.from("User").update(update).eq("id",u.id);if(x.error)throw new Error(x.error.message);if(typeof b.publicDiscoverable==="boolean"){const p=await sb.from("Profile").select("id").eq("userId",u.id).maybeSingle();if(p.error)throw new Error(p.error.message);const payload:any={userId:u.id,publicDiscoverable:b.publicDiscoverable};if(p.data?.id)payload.id=p.data.id;const y=await sb.from("Profile").upsert(payload,{onConflict:"userId"});if(y.error)throw new Error(y.error.message);}return NextResponse.json({ok:true});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Impossible d'enregistrer la vitrine."},{status:500});}}
