"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabaseClient } from "../../../lib/supabase";
import { PARTNER_NAV } from "../../../components/BottomNav";
import BottomNav from "../../../components/BottomNav";
import PageHeader from "../../../components/PageHeader";

type Commission={id:string;event:string;amount:number;currency:string;status:string;createdAt:string};
export default function PartnerPayment(){const router=useRouter();const [items,setItems]=useState<Commission[]>([]);const [totals,setTotals]=useState({payable:0,paid:0,pending:0});const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");useEffect(()=>{(async()=>{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){router.replace("/");return;}const r=await fetch("/api/partner/commissions",{headers:{Authorization:`Bearer ${s.data.session.access_token}`}});const b=await r.json().catch(()=>({}));if(!r.ok)setMessage(b.message||"Historique indisponible.");else{setItems(b.commissions||[]);setTotals(b.totals||{payable:0,paid:0,pending:0});}setLoading(false)})()},[router]);return <main className="relative min-h-[100dvh] bg-white pb-28 text-navy"><PageHeader label="Paiements" eyebrow="PARTNER" onBack={()=>router.push("/partner")} /><div className="mx-auto max-w-3xl px-5 py-6"><h1 className="font-heading text-2xl font-extrabold">Historique des paiements</h1><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-emerald-50 p-3"><b>{totals.payable.toLocaleString("fr-FR")}</b><span className="block text-[10px]">À payer</span></div><div className="rounded-2xl bg-blue-50 p-3"><b>{totals.paid.toLocaleString("fr-FR")}</b><span className="block text-[10px]">Payé</span></div><div className="rounded-2xl bg-amber-50 p-3"><b>{totals.pending.toLocaleString("fr-FR")}</b><span className="block text-[10px]">En attente</span></div></div>{loading?<p className="mt-6 text-sm text-jobly-gray">Chargement…</p>:message?<p className="mt-6 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-600">{message}</p>:<div className="mt-5 space-y-2">{items.length?items.map(x=><div key={x.id} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-4"><div className="flex-1"><b className="text-sm">{x.event}</b><span className="block text-xs text-jobly-gray">{new Date(x.createdAt).toLocaleDateString("fr-FR")} · {x.status}</span></div><strong>{x.amount.toLocaleString("fr-FR")} {x.currency}</strong></div>):<div className="rounded-2xl bg-slate-50 p-6 text-center text-sm text-jobly-gray">Aucun mouvement de commission pour le moment.</div>}</div>}<p className="mt-5 text-xs text-jobly-gray">Le versement Mobile Money dépend de l'activation de la brique Billing. Les commissions affichées ici restent consultables sans simuler un paiement.</p></div><BottomNav active="/partner/payment" items={PARTNER_NAV}/></main>}
