"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import QRCode from "qrcode";
import {getSupabaseClient} from "@/lib/supabase";
import PageHeader from "@/components/PageHeader";
import BottomNav from "@/components/BottomNav";
import TalentBackground from "@/components/TalentBackground";
export default function JoblyId(){const router=useRouter();const [id,setId]=useState("");const [qr,setQr]=useState("");const [name,setName]=useState("Profil Jobly");useEffect(()=>{(async()=>{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){router.replace("/");return}const u=s.data.session.user;setId(u.id);setName((u.user_metadata?.full_name||u.email||"Profil Jobly") as string);const opaque=`JOBLY-${u.id.replaceAll("-","").slice(0,12).toUpperCase()}`;QRCode.toDataURL(`${window.location.origin}/join?ref=${opaque}`,{width:240,margin:2}).then(setQr).catch(()=>{})})()},[router]);return <main className="talent-shell relative min-h-[100dvh] bg-[#F7FAFF] pb-28 text-navy"><TalentBackground/><div className="relative z-10"><PageHeader label="Jobly ID / QR" eyebrow="JOBLY" initial="J" onBack={()=>router.push("/dashboard")} theme="talent"/><div className="mx-auto max-w-md px-5 py-6"><div className="rounded-[30px] bg-white p-6 text-center shadow-sm border border-blue-100"><span className="rounded-full bg-[#FFF4BF] px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#735700]">Identité professionnelle portable</span><h1 className="mt-4 text-2xl font-black">{name}</h1><p className="mt-2 text-xs text-slate-500">Ton identifiant Jobly ne met pas de données sensibles dans le QR.</p>{qr&&<img src={qr} alt="QR Jobly ID" className="mx-auto mt-5 rounded-2xl"/>}<p className="mt-4 break-all rounded-xl bg-slate-50 p-3 font-mono text-[10px] text-slate-500">{id}</p><button onClick={()=>router.push("/talent/profile")} className="mt-4 w-full rounded-2xl bg-jobly-blue py-3 font-black text-white">Voir mon profil →</button></div></div></div><BottomNav active="/dashboard"/></main>}
