import { NextRequest, NextResponse } from "next/server";
import { adminClient, ensureUser, getAuthUser, newId } from "../../../lib/server-auth";
import { checkWeeklyApplicationQuota } from "../../../lib/entitlements";

const MAX_OFFER_AGE_DAYS = 60;

type ApplicationRow = { id:string; userId:string; jobId:string|null; recruiterJobId:string|null; status:string; proofUrl:string|null; viewedAt:string|null; interviewAt:string|null; statusSource:string; createdAt:string; updatedAt:string };
function statusLabel(status:string){switch(status){case "DISCOVERED":return "Brouillon";case "SUBMITTED":return "En attente";case "ACKNOWLEDGED":return "Vu";case "INTERVIEW":return "Entretien";case "OFFER":return "Acceptée";case "REJECTED":return "Refusée";default:return status;}}
function addMonths(date:Date, months:number):Date { const copy=new Date(date); const originalDay=copy.getDate(); copy.setDate(1); copy.setMonth(copy.getMonth()+months); const lastDay=new Date(copy.getFullYear(),copy.getMonth()+1,0).getDate(); copy.setDate(Math.min(originalDay,lastDay)); return copy; }
function isFresh(publishedAt:string|null|undefined,deadline:string|null|undefined,createdAt:string){if(deadline)return new Date(deadline).getTime()>=Date.now();const base=new Date(publishedAt||createdAt);return Number.isFinite(base.getTime())&&Date.now()<=addMonths(base,2).getTime()&&Date.now()-base.getTime()<=MAX_OFFER_AGE_DAYS*24*60*60*1000;}
function isOpen(deadline:string|null|undefined){return !deadline||new Date(deadline).getTime()>=Date.now();}

export async function GET(request:NextRequest){try{const authUser=await getAuthUser(request);if(!authUser)return NextResponse.json({message:"Session requise."},{status:401});const supabase=adminClient();const user=await ensureUser(supabase,authUser);const {data:apps,error}=await supabase.from("Application").select("*").eq("userId",user.id).order("updatedAt",{ascending:false});if(error)throw new Error(error.message);const applications=(apps as ApplicationRow[])||[];const jobIds=applications.map(a=>a.jobId).filter(Boolean) as string[];const recruiterJobIds=applications.map(a=>a.recruiterJobId).filter(Boolean) as string[];const [jobsRes,recruiterJobsRes]=await Promise.all([jobIds.length?supabase.from("Job").select("id,title,location,contractType,remoteMode,companyId").in("id",jobIds):Promise.resolve({data:[],error:null}),recruiterJobIds.length?supabase.from("RecruiterJob").select("id,title,location,contract,remoteMode,companyName").in("id",recruiterJobIds):Promise.resolve({data:[],error:null})]);if(jobsRes.error)throw new Error(jobsRes.error.message);if(recruiterJobsRes.error)throw new Error(recruiterJobsRes.error.message);const companyIds=Array.from(new Set((jobsRes.data||[]).map((j:any)=>j.companyId).filter(Boolean)));const companiesRes=companyIds.length?await supabase.from("Company").select("id,name,logoUrl,description,website").in("id",companyIds):{data:[],error:null};if(companiesRes.error)throw new Error(companiesRes.error.message);const jobsById=new Map((jobsRes.data||[]).map((j:any)=>[j.id,j]));const recruiterJobsById=new Map((recruiterJobsRes.data||[]).map((j:any)=>[j.id,j]));const companiesById=new Map((companiesRes.data||[]).map((c:any)=>[c.id,c]));const results=applications.map(app=>{const isDiscovery=!!app.jobId;const job=isDiscovery?jobsById.get(app.jobId as string):recruiterJobsById.get(app.recruiterJobId as string);const company=isDiscovery&&job?.companyId?companiesById.get(job.companyId):null;return{id:app.id,source:isDiscovery?"discovery":"recruiter",jobId:app.jobId,recruiterJobId:app.recruiterJobId,status:app.status,statusLabel:statusLabel(app.status),statusSource:app.statusSource,proofUrl:app.proofUrl,viewedAt:app.viewedAt,interviewAt:app.interviewAt,createdAt:app.createdAt,updatedAt:app.updatedAt,job:job?{title:job.title,location:job.location,contractType:job.contract,remoteMode:job.remoteMode,companyName:isDiscovery?company?.name??null:job.companyName}:null};});const counters={envoyees:results.filter(a=>a.status!=="DISCOVERED").length,vues:results.filter(a=>["ACKNOWLEDGED","INTERVIEW","OFFER","REJECTED"].includes(a.status)).length,entretien:results.filter(a=>a.status==="INTERVIEW").length};return NextResponse.json({applications:results,counters});}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Impossible de charger les candidatures."},{status:500});}}

export async function POST(request:NextRequest){try{const authUser=await getAuthUser(request);if(!authUser)return NextResponse.json({message:"Session requise."},{status:401});const supabase=adminClient();const user=await ensureUser(supabase,authUser);const body=await request.json();const source=body.source==="recruiter"?"recruiter":body.source==="discovery"?"discovery":null;const targetId=typeof body.jobId==="string"?body.jobId.trim():"";const proofUrl=typeof body.proofUrl==="string"&&body.proofUrl.trim()?body.proofUrl.trim():null;if(!source||!targetId)return NextResponse.json({message:"Offre invalide (source et identifiant requis)."},{status:400});

 let offer:any=null;
 if(source==="discovery"){
  const {data,error}=await supabase.from("Job").select("id,title,isActive,applicationReady,applicationProfile,createdAt,sourcePublishedAt,deadline,source,sourceUrl").eq("id",targetId).maybeSingle();if(error)throw new Error(error.message);offer=data;
  if(!offer||!offer.isActive)return NextResponse.json({message:"Cette offre n'est plus active."},{status:410});
  if(!offer.applicationReady)return NextResponse.json({message:"J'IA ne peut pas encore candidater à cette offre."},{status:422});
  if(!isFresh(offer.sourcePublishedAt,offer.deadline,offer.createdAt))return NextResponse.json({message:"Cette offre n'est plus diffusée par Jobly."},{status:410});
  if(!isOpen(offer.deadline))return NextResponse.json({message:"La date limite de candidature est dépassée."},{status:410});
 }else{
  const {data,error}=await supabase.from("RecruiterJob").select("id,title,status,applicationReady,applicationProfile,createdAt").eq("id",targetId).maybeSingle();if(error)throw new Error(error.message);offer=data;
  if(!offer||offer.status!=="published")return NextResponse.json({message:"Cette offre Jobly n'est plus publiée."},{status:410});
  if(!offer.applicationReady)return NextResponse.json({message:"J'IA ne peut pas encore candidater à cette offre."},{status:422});
  if(!isFresh(null,null,offer.createdAt))return NextResponse.json({message:"Cette offre n'est plus diffusée par Jobly."},{status:410});
 }
 if(proofUrl){const quota=await checkWeeklyApplicationQuota(supabase,user.id);if(!quota.allowed)return NextResponse.json({message:quota.message,quota:{used:quota.used,limit:quota.limit}},{status:429});}
 const payload:Record<string,unknown>={id:newId(),userId:user.id,jobId:source==="discovery"?targetId:null,recruiterJobId:source==="recruiter"?targetId:null,language:"fr",status:proofUrl?"SUBMITTED":"DISCOVERED",proofUrl,submittedAt:proofUrl?new Date().toISOString():null,statusSource:"CANDIDATE",updatedAt:new Date().toISOString()};
 const {data,error}=await supabase.from("Application").insert(payload).select("*").single();if(error){if(error.code==="23505")return NextResponse.json({message:"Vous avez déjà une candidature pour cette offre."},{status:409});throw new Error(error.message);}return NextResponse.json({application:data,applicationProfile:offer.applicationProfile||{}});
 }catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Impossible d'enregistrer la candidature."},{status:500});}}
