import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import crypto from "node:crypto";
const BUCKET="talent-pitches",MAX=4*1024*1024,ALLOWED=new Set(["video/mp4","video/webm","video/quicktime"]);
function admin(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase serveur non configuré.");return createClient(u,k,{auth:{autoRefreshToken:false,persistSession:false}});}
async function auth(req:NextRequest){const t=req.headers.get("authorization")?.replace(/^Bearer\\s+/i,"");if(!t)return null;const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)throw new Error("Supabase client non configuré.");const sb=createClient(u,k,{auth:{autoRefreshToken:false,persistSession:false}});return (await sb.auth.getUser(t)).data.user||null;}
async function user(sb:any,au:any){const r=await sb.from("User").select("*").eq("authUserId",au.id).maybeSingle();if(r.error)throw new Error(r.error.message);if(r.data)return r.data;const x=await sb.from("User").insert({id:crypto.randomUUID(),authUserId:au.id,email:au.email??null,updatedAt:new Date().toISOString()}).select("*").single();if(x.error)throw new Error(x.error.message);return x.data;}
async function plan(sb:any,id:string){const r=await sb.from("Subscription").select("plan,updatedAt").eq("userId",id).eq("status","ACTIVE").order("updatedAt",{ascending:false}).limit(1).maybeSingle();const p=String(r.data?.plan||"FREE").toUpperCase();return p==="PRO"?"PRO":p.indexOf("PREMIUM")===0?"PREMIUM":"FREE";}
async function bucket(sb:any){const r=await sb.storage.listBuckets();if(r.error)throw new Error(r.error.message);if(!r.data?.some((b:any)=>b.name===BUCKET)){const x=await sb.storage.createBucket(BUCKET,{public:true,fileSizeLimit:String(MAX),allowedMimeTypes:Array.from(ALLOWED)});if(x.error&&!/already exists/i.test(x.error.message))throw new Error(x.error.message);}}
export async function POST(req:NextRequest){try{const au=await auth(req);if(!au)return NextResponse.json({message:"Session requise."},{status:401});const sb=admin(),u=await user(sb,au),p=await plan(sb,u.id),max=p==="PRO"?20000:p==="PREMIUM"?10000:0;if(!max)return NextResponse.json({message:"Le Pitch est disponible avec Pro ou Premium."},{status:403});const form=await req.formData(),f=form.get("file");if(!(f instanceof File))return NextResponse.json({message:"Vidéo manquante."},{status:400});if(!ALLOWED.has(f.type))return NextResponse.json({message:"MP4, WebM ou MOV uniquement."},{status:415});if(f.size>MAX)return NextResponse.json({message:"4 Mo maximum."},{status:413});const d=Number(form.get("durationMs")||0);if(!Number.isFinite(d)||d<1000||d>max)return NextResponse.json({message:"Pitch : "+max/1000+"s maximum pour "+p+"."},{status:422});await bucket(sb);const ext=f.type==="video/webm"?"webm":f.type==="video/quicktime"?"mov":"mp4",path=u.id+"/"+Date.now()+"-"+crypto.randomUUID()+"."+ext;const up=await sb.storage.from(BUCKET).upload(path,new Uint8Array(await f.arrayBuffer()),{contentType:f.type,upsert:false,cacheControl:"31536000"});if(up.error)throw new Error(up.error.message);const url=sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl,old=u.pitchVideoStoragePath,now=new Date().toISOString(),x=await sb.from("User").update({pitchVideoUrl:url,pitchVideoStoragePath:path,pitchVideoDurationMs:Math.round(d),pitchVideoUpdatedAt:now,updatedAt:now}).eq("id",u.id);if(x.error){await sb.storage.from(BUCKET).remove([path]);throw new Error(x.error.message);}if(old)await sb.storage.from(BUCKET).remove([old]);return NextResponse.json({ok:true,pitchVideoUrl:url,pitchVideoDurationMs:Math.round(d),plan:p});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Impossible d'enregistrer le Pitch."},{status:500});}}
export async function DELETE(req:NextRequest){try{const au=await auth(req);if(!au)return NextResponse.json({message:"Session requise."},{status:401});const sb=admin(),u=await user(sb,au);if(u.pitchVideoStoragePath)await sb.storage.from(BUCKET).remove([u.pitchVideoStoragePath]);const x=await sb.from("User").update({pitchVideoUrl:null,pitchVideoStoragePath:null,pitchVideoDurationMs:null,pitchVideoUpdatedAt:null,updatedAt:new Date().toISOString()}).eq("id",u.id);if(x.error)throw new Error(x.error.message);return NextResponse.json({ok:true});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Suppression impossible."},{status:500});}}
