 "use client";
import { useEffect,useMemo,useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { getSupabaseClient } from "@/lib/supabase";
import BottomNav from "../../components/BottomNav";
import PageHeader from "../../components/PageHeader";
import TalentBackground from "../../components/TalentBackground";
import ScoreRing from "../../components/ScoreRing";

type Exp={company:string;title:string;startDate:string;endDate:string;description:string};
type Edu={institution:string;degree:string;field:string;startDate:string;endDate:string};
const blankExp=():Exp=>({company:"",title:"",startDate:"",endDate:"",description:""});
const blankEdu=():Edu=>({institution:"",degree:"",field:"",startDate:"",endDate:""});
const Field=({label,children}:{label:string;children:ReactNode})=><label className="block"><span className="mb-2 block text-sm font-extrabold text-navy">{label}</span>{children}</label>;
const input="field w-full";
function Chips({label,items,setItems,placeholder}:{label:string;items:string[];setItems:(x:string[])=>void;placeholder:string}){const [v,setV]=useState(""); const add=()=>{const x=v.trim();if(x&&!items.includes(x))setItems([...items,x]);setV("")};return <Field label={label}><div className="flex min-h-[50px] flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2.5">{items.map(x=><button type="button" key={x} onClick={()=>setItems(items.filter(y=>y!==x))} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-jobly-blue">{x} ×</button>)}<input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}} onBlur={add} placeholder={placeholder} className="min-w-[130px] flex-1 bg-transparent px-1 text-sm outline-none"/></div></Field>}

export default function CareerBrain(){
 const router=useRouter(); const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 const [tab,setTab]=useState("profil"); const [user,setUser]=useState({displayName:"",email:"",englishLevel:"",licences:[] as string[],avatarUrl:""});
 const [p,setP]=useState({headline:"",summary:"",location:"",targetRoles:[] as string[],preferredSectors:[] as string[]});
 const [exps,setExps]=useState<Exp[]>([]),[skills,setSkills]=useState<{name:string;level:string}[]>([]),[edu,setEdu]=useState<Edu[]>([]);
 useEffect(()=>{(async()=>{try{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){router.replace("/");return}const r=await fetch("/api/profile",{headers:{Authorization:`Bearer ${s.data.session.access_token}`}}),b=await r.json();if(!r.ok)throw Error(b.message);setUser({displayName:b.user.displayName||"",email:b.user.email||"",englishLevel:b.user.englishLevel||"",licences:b.user.licences||[],avatarUrl:b.user.avatarUrl||""});setP({headline:b.profile.headline||"",summary:b.profile.summary||"",location:b.profile.location||"",targetRoles:b.profile.targetRoles||[],preferredSectors:b.profile.preferredSectors||[]});setExps((b.experiences||[]).map((x:any)=>({...x,startDate:x.startDate?.slice(0,10)||"",endDate:x.endDate?.slice(0,10)||""})));setSkills(b.skills||[]);setEdu((b.education||[]).map((x:any)=>({...x,startDate:x.startDate?.slice(0,10)||"",endDate:x.endDate?.slice(0,10)||""})))}catch(e){setMsg(e instanceof Error?e.message:"Erreur de chargement")}finally{setLoading(false)}})()},[router]);
 const score=useMemo(()=>{let n=0;if(user.displayName)n+=15;if(p.headline)n+=10;if(p.summary)n+=15;if(p.location)n+=10;if(p.targetRoles.length)n+=10;if(p.preferredSectors.length)n+=10;if(skills.filter(x=>x.name).length)n+=15;if(exps.length)n+=10;if(edu.length)n+=5;return n},[user,p,skills,exps,edu]);
 async function save(section: "profil" | "objectif" | "experience" | "skills" | "formation" | "all" = "all", next?: string){setSaving(true);setMsg("");try{const s=await getSupabaseClient().auth.getSession();if(!s.data.session)throw Error("Session requise.");const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${s.data.session.access_token}`},body:JSON.stringify({section,...user,...p,experiences:exps,skills,education:edu})});const b=await r.json();if(!r.ok)throw Error(b.message);setMsg("Section enregistrée ✓");if(next)setTimeout(()=>setTab(next),120)}catch(e){setMsg(e instanceof Error?e.message:"Erreur d'enregistrement")}finally{setSaving(false)}}
 if(loading)return <main className="talent-shell grid min-h-screen place-items-center bg-[#F7FAFF] font-bold text-navy">Chargement…</main>;
 const tabs=[["profil","Profil"],["objectif","Objectif"],["experience","Expériences"],["skills","Compétences"],["formation","Formation"]];
 return <main className="talent-shell relative min-h-screen overflow-hidden bg-[#F7FAFF] pb-24 text-navy"><TalentBackground /><div className="relative z-10"><PageHeader eyebrow="Career Brain" label="Ton profil professionnel" initial={(user.displayName||"J").charAt(0).toUpperCase()} avatarUrl={user.avatarUrl} theme="talent" />
 <div className="mx-auto w-full max-w-6xl px-4 py-5 sm:px-6 lg:px-8"><header className="mb-5 flex items-center justify-end"><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-extrabold text-jobly-blue">Career Brain</span></header><div className="grid gap-5 lg:grid-cols-[245px_1fr]"><aside className="h-max rounded-[24px] border border-slate-100 bg-white p-4 shadow-sm lg:sticky lg:top-24"><div className="flex items-center gap-3 rounded-2xl bg-blue-50 p-4"><ScoreRing value={score} size={60} /><div><div className="text-xs font-bold text-slate-500">Career Score</div><div className="text-2xl font-black text-jobly-blue">{score}<span className="text-sm">/100</span></div></div></div><nav className="mt-4 space-y-1">{tabs.map(([id,label])=><button type="button" key={id} onClick={()=>setTab(id)} className={`w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold ${tab===id?"bg-blue-50 text-jobly-blue":"text-slate-600"}`}>{label}</button>)}</nav><button type="button" onClick={()=>save()} disabled={saving} className="mt-4 w-full rounded-2xl bg-jobly-blue py-3 text-sm font-extrabold text-white">{saving?"Enregistrement…":"Enregistrer"}</button>{msg&&<p className="mt-3 text-center text-xs font-semibold text-slate-600">{msg}</p>}</aside>
 <section className="talent-card rounded-[28px] border border-slate-100 bg-white p-5 shadow-sm sm:p-8">
 {tab==="profil"&&<div className="space-y-5"><h1 className="text-2xl font-black">Ton identité professionnelle</h1><p className="text-sm text-slate-500">Construisons une base fiable pour ton Career Brain.</p><Field label="Nom complet"><input className={input} value={user.displayName} onChange={e=>setUser({...user,displayName:e.target.value})} placeholder="Ex. Marie Nganou"/></Field><Field label="E-mail"><input className={input+" bg-slate-50"} disabled value={user.email}/></Field><Field label="Ville / localisation"><input className={input} value={p.location} onChange={e=>setP({...p,location:e.target.value})} placeholder="Ex. Yaoundé, Cameroun"/></Field><Field label="Titre professionnel"><input className={input} value={p.headline} onChange={e=>setP({...p,headline:e.target.value})} placeholder="Ex. Assistante administrative"/></Field><Field label="Présentation"><textarea className={input+" resize-y"} rows={5} value={p.summary} onChange={e=>setP({...p,summary:e.target.value})} placeholder="Ton parcours, tes forces et ce que tu recherches…"/></Field><button type="button" onClick={()=>save("profil","objectif")} disabled={saving} className="rounded-2xl bg-jobly-yellow px-5 py-2 text-sm font-bold text-navy shadow-[0_6px_16px_rgba(255,199,44,0.3)] transition-transform active:scale-[0.97]">{saving?"Enregistrement…":"Continuer →"}</button></div>}
 {tab==="objectif"&&<div className="space-y-5"><h1 className="text-2xl font-black">Objectif professionnel</h1><Chips label="Métiers ciblés" items={p.targetRoles} setItems={x=>setP({...p,targetRoles:x})} placeholder="Ex. Commercial + Entrée"/><Chips label="Secteurs préférés" items={p.preferredSectors} setItems={x=>setP({...p,preferredSectors:x})} placeholder="Ex. Banque + Entrée"/><Field label="Niveau d’anglais"><select className={input} value={user.englishLevel} onChange={e=>setUser({...user,englishLevel:e.target.value})}><option value="">Sélectionner</option><option>Débutant</option><option>Intermédiaire</option><option>Avancé</option><option>Bilingue</option></select></Field><Chips label="Permis / licences" items={user.licences} setItems={x=>setUser({...user,licences:x})} placeholder="Ex. Permis B + Entrée"/><button type="button" onClick={()=>save("objectif","experience")} disabled={saving} className="rounded-2xl bg-jobly-yellow px-5 py-2 text-sm font-bold text-navy shadow-[0_6px_16px_rgba(255,199,44,0.3)] transition-transform active:scale-[0.97]">{saving?"Enregistrement…":"Continuer →"}</button></div>}
 {tab==="experience"&&<div className="space-y-5"><div><h1 className="text-2xl font-black">Expériences</h1><p className="text-sm text-slate-500">Uniquement des informations réelles.</p></div>{exps.map((x,i)=><div className="space-y-3 rounded-2xl border p-4" key={i}><div className="flex justify-between font-bold">Expérience {i+1}<button type="button" onClick={()=>setExps(exps.filter((_,j)=>j!==i))} className="text-xs text-red-500">Supprimer</button></div><input className={input} value={x.title} onChange={e=>{let a=[...exps];a[i]={...a[i],title:e.target.value};setExps(a)}} placeholder="Poste"/><input className={input} value={x.company} onChange={e=>{let a=[...exps];a[i]={...a[i],company:e.target.value};setExps(a)}} placeholder="Entreprise"/><div className="grid gap-3 sm:grid-cols-2"><input type="date" className={input} value={x.startDate} onChange={e=>{let a=[...exps];a[i]={...a[i],startDate:e.target.value};setExps(a)}}/><input type="date" className={input} value={x.endDate} onChange={e=>{let a=[...exps];a[i]={...a[i],endDate:e.target.value};setExps(a)}}/></div><textarea className={input} rows={3} value={x.description} onChange={e=>{let a=[...exps];a[i]={...a[i],description:e.target.value};setExps(a)}} placeholder="Responsabilités et réalisations"/></div>)}<button type="button" onClick={()=>setExps([...exps,blankExp()])} className="rounded-2xl border-2 border-dashed px-4 py-3 text-sm font-extrabold text-jobly-blue">+ Ajouter une expérience</button><button type="button" onClick={()=>save("experience","skills")} disabled={saving} className="rounded-2xl bg-jobly-yellow px-5 py-2 text-sm font-bold text-navy shadow-[0_6px_16px_rgba(255,199,44,0.3)] transition-transform active:scale-[0.97]">{saving?"Enregistrement…":"Continuer →"}</button></div>}
 {tab==="skills"&&<div className="space-y-5"><h1 className="text-2xl font-black">Compétences</h1>{skills.map((x,i)=><div className="flex gap-2" key={i}><input className={input} value={x.name} onChange={e=>{let a=[...skills];a[i]={...a[i],name:e.target.value};setSkills(a)}} placeholder="Ex. Excel"/><select className="field w-36" value={x.level||""} onChange={e=>{let a=[...skills];a[i]={...a[i],level:e.target.value};setSkills(a)}}><option value="">Niveau</option><option>Débutant</option><option>Intermédiaire</option><option>Avancé</option><option>Expert</option></select><button type="button" onClick={()=>setSkills(skills.filter((_,j)=>j!==i))}>×</button></div>)}<button type="button" onClick={()=>setSkills([...skills,{name:"",level:""}])} className="rounded-2xl border-2 border-dashed px-4 py-3 text-sm font-extrabold text-jobly-blue">+ Ajouter une compétence</button><button type="button" onClick={()=>save("skills","formation")} disabled={saving} className="rounded-2xl bg-jobly-yellow px-5 py-2 text-sm font-bold text-navy shadow-[0_6px_16px_rgba(255,199,44,0.3)] transition-transform active:scale-[0.97]">{saving?"Enregistrement…":"Continuer →"}</button></div>}
 {tab==="formation"&&<div className="space-y-5"><h1 className="text-2xl font-black">Formation</h1>{edu.map((x,i)=><div className="space-y-3 rounded-2xl border p-4" key={i}><div className="flex justify-between font-bold">Formation {i+1}<button type="button" onClick={()=>setEdu(edu.filter((_,j)=>j!==i))} className="text-xs text-red-500">Supprimer</button></div><input className={input} value={x.institution} onChange={e=>{let a=[...edu];a[i]={...a[i],institution:e.target.value};setEdu(a)}} placeholder="Établissement"/><div className="grid gap-3 sm:grid-cols-2"><input className={input} value={x.degree} onChange={e=>{let a=[...edu];a[i]={...a[i],degree:e.target.value};setEdu(a)}} placeholder="Diplôme"/><input className={input} value={x.field} onChange={e=>{let a=[...edu];a[i]={...a[i],field:e.target.value};setEdu(a)}} placeholder="Spécialité"/></div><div className="grid gap-3 sm:grid-cols-2"><input type="date" className={input} value={x.startDate} onChange={e=>{let a=[...edu];a[i]={...a[i],startDate:e.target.value};setEdu(a)}}/><input type="date" className={input} value={x.endDate} onChange={e=>{let a=[...edu];a[i]={...a[i],endDate:e.target.value};setEdu(a)}}/></div></div>)}<button type="button" onClick={()=>setEdu([...edu,blankEdu()])} className="rounded-2xl border-2 border-dashed px-4 py-3 text-sm font-extrabold text-jobly-blue">+ Ajouter une formation</button><button type="button" onClick={()=>save("formation")} disabled={saving} className="rounded-2xl bg-jobly-yellow px-5 py-2 text-sm font-bold text-navy shadow-[0_6px_16px_rgba(255,199,44,0.3)] transition-transform active:scale-[0.97]">{saving?"Enregistrement…":"Continuer →"}</button></div>}
 <div className="mt-8 flex justify-end"><button type="button" onClick={()=>save("all")} className="rounded-2xl bg-jobly-blue px-6 py-3 font-extrabold text-white">{saving?"Enregistrement…":"Enregistrer tout le profil"}</button></div>
 <div className="mt-6 border-t border-slate-100 pt-5"><h2 className="font-extrabold">J'IA — Coaching carrière</h2><p className="mt-1 text-xs text-jobly-gray">Prépare tes candidatures avec l'assistant Jobly.</p><div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-3">{[["Coach IA","/ai/companion"],["Simulateur d'entretien","/ai/interview"],["Assistant candidature","/ai/application"]].map(([label,href])=><button key={href} type="button" onClick={()=>router.push(href)} className="rounded-2xl border border-slate-100 bg-white px-3 py-3 text-left shadow-sm"><span className="block text-xs font-black text-jobly-blue">{label}</span><span className="mt-1 block text-[10px] text-slate-500">Ouvrir →</span></button>)}</div></div>
 </section></div></div></div><BottomNav active="/career-brain" /></main>
}
