export type IntelligenceConfidence="HIGH"|"MEDIUM"|"LOW";
export type JiaStage="OBSERVATION"|"INSIGHT"|"HYPOTHESIS"|"RECOMMENDATION"|"ACTION"|"OUTCOME"|"LEARNING";
export type Signal={id:string;type:string;title:string;detail:string;value?:number|null;baseline?:number|null;unit?:string;occurredAt?:string;confidence?:IntelligenceConfidence;metadata?:Record<string,unknown>};
export type Recommendation={id:string;title:string;reason:string;priority:"HIGH"|"MEDIUM"|"LOW";confidence:IntelligenceConfidence;actionType:"REVIEW"|"LEARN"|"APPLY"|"FOLLOW_UP"|"VERIFY";entityType?:string;entityId?:string|null;expiresAt?:string|null};
const pct=(current:number,baseline:number)=>baseline===0?(current===0?0:null):Math.round(((current-baseline)/baseline)*1000)/10;
export function comparePeriods(current:number,previous:number){return{current,previous,delta:current-previous,pct:pct(current,previous),direction:current>previous?"UP":current<previous?"DOWN":"FLAT"} as const;}
export function detectAnomaly(current:number,baseline:number,thresholdPct=30){const change=pct(current,baseline);if(change===null)return{isAnomaly:false,changePct:null,severity:"NONE" as const};const magnitude=Math.abs(change);return{isAnomaly:magnitude>=thresholdPct,changePct:change,severity:magnitude>=100?"HIGH":magnitude>=thresholdPct?"MEDIUM":"NONE"} as const;}
export function scoreConfidence(signals:Signal[]){if(!signals.length)return"LOW" as IntelligenceConfidence;const verified=signals.filter(s=>s.confidence==="HIGH").length;const ratio=verified/signals.length;return ratio>=.67?"HIGH":ratio>=.34?"MEDIUM":"LOW";}
export function buildNextBestActions(signals:Signal[],now=new Date()):Recommendation[]{const out:Recommendation[]=[];for(const s of signals){const confidence=s.confidence||"LOW";if(s.type==="APPLICATION_STALLED")out.push({id:`followup-${s.id}`,title:"Faire le suivi de cette candidature",reason:s.detail,priority:"HIGH",confidence,actionType:"FOLLOW_UP",entityType:"APPLICATION",entityId:s.id,expiresAt:new Date(now.getTime()+7*86400000).toISOString()});else if(s.type==="APPLICATION_INTERVIEW")out.push({id:`interview-${s.id}`,title:"Préparer l’entretien",reason:s.detail,priority:"HIGH",confidence,actionType:"APPLY",entityType:"APPLICATION",entityId:s.id});else if(s.type==="CAREER_GAP")out.push({id:`learn-${s.id}`,title:"Travailler ce gap de carrière",reason:s.detail,priority:"MEDIUM",confidence,actionType:"LEARN",entityType:"CAREER",entityId:s.id});else if(s.type==="OFFER_MATCH")out.push({id:`apply-${s.id}`,title:"Évaluer cette opportunité",reason:s.detail,priority:"MEDIUM",confidence,actionType:"APPLY",entityType:"JOB",entityId:s.id});else if(s.type==="SEARCH_PATTERN")out.push({id:`search-${s.id}`,title:"Transformer tes recherches en plan",reason:s.detail,priority:"MEDIUM",confidence,actionType:"REVIEW",entityType:"CAREER",entityId:null});else if(s.type==="LEARNING_CONTINUITY")out.push({id:`learning-${s.id}`,title:"Continuer cet apprentissage",reason:s.detail,priority:"MEDIUM",confidence,actionType:"LEARN",entityType:"CAREER",entityId:null});else if(s.type==="PROFILE_TO_OPPORTUNITY")out.push({id:`profile-${s.id}`,title:"Recalculer tes opportunités",reason:s.detail,priority:"HIGH",confidence,actionType:"REVIEW",entityType:"CAREER",entityId:null});}return out.sort((a,b)=>({HIGH:0,MEDIUM:1,LOW:2}[a.priority]-{HIGH:0,MEDIUM:1,LOW:2}[b.priority])).slice(0,5);}
export function buildLearningObservation(outcome:{success:boolean;signalId:string;detail:string},previousConfidence:IntelligenceConfidence="LOW"){return{stage:"LEARNING" as JiaStage,title:outcome.success?"Signal confirmé":"Signal à réviser",content:outcome.detail,confidence:outcome.success?"HIGH":previousConfidence,metadata:{sourceSignalId:outcome.signalId,learningPolicy:"CONTROLLED",autoPromoteToMemory:false}};}
export function summarizeTemporalSignals(signals:Signal[]){const anomalies=signals.map(s=>({...s,anomaly:s.baseline==null||s.value==null?null:detectAnomaly(s.value,s.baseline)})).filter(s=>s.anomaly?.isAnomaly);return{count:signals.length,anomalies,confidence:scoreConfidence(signals),generatedAt:new Date().toISOString()};}
