"use client";
import {useEffect,useState} from "react";
import MapPreview from "../../../../../components/mobility/MapPreview";
import {MOBILITY_STEPS} from "../../../../../lib/mobility";
import {getSupabaseClient} from "@/lib/supabase";

const docs=[["CNI","FRONT","CNI — recto"],["CNI","BACK","CNI — verso"],["PASSPORT",null,"Passeport"],["LOCATION_PLAN",null,"Plan de localisation"],["HONOR_COMMITMENT",null,"Lettre d'engagement sur l'honneur"]] as const;
const labels:Record<string,string>={PENDING:"Reçu",UNDER_REVIEW:"En vérification",VERIFIED:"Validé",REJECTED:"À corriger",EXPIRED:"Expiré"};
export default function StatusPage(){
 const [req,setReq]=useState<any>(null),[documents,setDocuments]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const raw=localStorage.getItem("jobly-mobility-request");if(!raw)return;const local=JSON.parse(raw);setReq(local);const s=await getSupabaseClient().auth.getSession();const token=s.data.session?.access_token;if(!token||!local?.id)return;const r=await fetch("/api/mobility/dossier?requestId="+encodeURIComponent(local.id),{headers:{Authorization:"Bearer "+token}});if(r.ok){const b=await r.json();setReq(b.request);setDocuments(b.documents||[]);setEvents(b.events||[]);localStorage.setItem("jobly-mobility-request",JSON.stringify(b.request));}};
 useEffect(()=>{load()},[]);
 async function upload(documentType:string,side:string|null,file:File){setBusy(true);setMessage("");try{const s=await getSupabaseClient().auth.getSession();const token=s.data.session?.access_token;if(!token)throw new Error("Session requise.");const fd=new FormData();fd.append("requestId",req.id);fd.append("documentType",documentType);if(side)fd.append("side",side);if(documentType==="CNI"||documentType==="PASSPORT"){const expiry=window.prompt("Date d'expiration (AAAA-MM-JJ)");if(!expiry)throw new Error("Date d'expiration requise.");fd.append("validUntil",expiry)}fd.append("file",file);const r=await fetch("/api/mobility/documents",{method:"POST",headers:{Authorization:"Bearer "+token},body:fd});const b=await r.json();if(!r.ok)throw new Error(b.message);await load()}catch(e){setMessage(e instanceof Error?e.message:"Upload impossible.")}finally{setBusy(false)}}
 const docFor=(type:string,side:string|null)=>documents.find(d=>d.documentType===type&&(d.side||null)===(side||null));
 return <section className="min-h-[100dvh] bg-transparent px-5 py-8"><div className="mx-auto max-w-4xl">
 <span className="rounded-full bg-[#FFF5CC] px-3 py-1 text-xs font-black text-[#8A6500]">DOSSIER MOBILITY</span>
 <h1 className="mt-4 text-3xl font-black">Ton dossier de mobilité</h1>
 <p className="mt-2 max-w-2xl text-sm text-slate-500">Un espace partagé pour suivre l'éligibilité, les pièces, les validations, le financement et ton arrivée au poste.</p>
 {!req?<div className="mt-7 rounded-[24px] border border-dashed p-8 text-center"><p className="font-black">Aucune demande</p><p className="mt-1 text-sm text-slate-500">Crée une demande Mobility pour ouvrir ton dossier.</p></div>:<>
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-[24px] bg-white p-5 shadow-sm border"><p className="text-xs font-black text-slate-400">Trajet</p><b>{req.departCity} → {req.arriveeCity}</b></div><div className="rounded-[24px] bg-white p-5 shadow-sm border"><p className="text-xs font-black text-slate-400">Salaire approuvé</p><b>{Number(req.salaryApproved||req.salary||0).toLocaleString()} {req.salaryCurrency||"XAF"}</b></div><div className="rounded-[24px] bg-[#FFF8D9] p-5 shadow-sm border"><p className="text-xs font-black text-slate-500">Seuil Mobility</p><b>{req.eligibilityThresholdPercent||50}%</b><p className="text-xs text-slate-500">Charge actuelle : {req.eligibilityBurdenPercent??"—"}%</p></div></div>
 <div className="mt-6 rounded-[24px] bg-white p-5 shadow-sm border"><h2 className="text-xl font-black">Progression</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{MOBILITY_STEPS.map((s,i)=>{const done=i+1<=Number(req.currentStep||1);return <div key={s} className="flex items-center gap-3"><span className={"h-3 w-3 rounded-full "+(done?"bg-[#0A3D9C]":"bg-slate-200")}/><span className={done?"font-black":"text-slate-400"}>{s}</span></div>})}</div></div>
 <div className="mt-6 rounded-[24px] bg-white p-5 shadow-sm border"><h2 className="text-xl font-black">Pièces justificatives</h2><p className="mt-1 text-sm text-slate-500">Les fichiers sont privés. Tu vois leur état de traitement et la prochaine action attendue.</p>{message&&<div className="mt-4 rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-600">{message}</div>}<div className="mt-5 grid gap-3">{docs.map(([type,side,label])=>{const d=docFor(type,side);return <div key={label} className="flex flex-col gap-3 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b>{label}</b><p className="text-xs text-slate-500">{d?labels[d.status]:"À fournir"}</p>{d?.rejectionReason&&<p className="text-xs font-bold text-red-600">{d.rejectionReason}</p>}</div><label className="cursor-pointer rounded-full bg-[#0A3D9C] px-4 py-2 text-center text-xs font-black text-white">{busy?"Traitement…":d?.status==="VERIFIED"?"Remplacer":"Ajouter"}<input type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(type,side,f);e.currentTarget.value=""}}/></label></div>})}</div></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-[24px] bg-white p-5 shadow-sm border"><h2 className="text-xl font-black">Trajet</h2><div className="mt-4"><MapPreview from={{lat:req.departLat,lng:req.departLng,label:req.departCity}} to={{lat:req.arriveeLat,lng:req.arriveeLng,label:req.arriveeCity}}/></div></div><div className="rounded-[24px] bg-white p-5 shadow-sm border"><h2 className="text-xl font-black">Historique du traitement</h2><div className="mt-4 space-y-4">{events.length?events.map((e:any)=><div key={e.id} className="border-l-2 border-slate-200 pl-4"><p className="text-xs text-slate-400">{new Date(e.createdAt).toLocaleString("fr-FR")}</p><b>{e.title}</b><p className="text-sm text-slate-500">{e.description}</p></div>):<p className="text-sm text-slate-500">Les événements de traitement apparaîtront ici.</p>}</div></div></div>
 </>}</div></section>
}