"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import PageHeader from "@/components/PageHeader";
const statuses=["DRAFT","GUARANTEED","SUBSIDY_VALIDATED","PAID","REJECTED","CLOSED"];
export default function AdminMobility(){const router=useRouter();const [rows,setRows]=useState<any[]>([]),[status,setStatus]=useState(""),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);const s=await (await import("@/lib/supabase")).getSupabaseClient().auth.getSession();const t=s.data.session?.access_token;if(!t)return;const r=await fetch("/api/mobility/admin/dossiers"+(status?"?status="+status:""),{headers:{Authorization:"Bearer "+t}});if(r.ok)setRows((await r.json()).requests||[]);setLoading(false)};useEffect(()=>{load()},[status]);
return <main className="min-h-[100dvh] bg-[#F7FAFF] pb-8"><PageHeader eyebrow="ADMIN" label="Mobility" onBack={()=>router.push("/admin")}/><div className="px-5 py-8"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-black">Mobility — Administration</h1><p className="mt-2 text-sm text-slate-500">Validation centrale des dossiers, éligibilité, pièces et décisions.</p>
<div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>setStatus("")} className="rounded-full bg-slate-900 px-4 py-2 text-xs font-black text-white">Tous</button>{statuses.map(s=><button key={s} onClick={()=>setStatus(s)} className="rounded-full border px-4 py-2 text-xs font-black">{s}</button>)}</div>
{loading?<p className="mt-8">Chargement…</p>:<div className="mt-6 grid gap-3">{rows.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="w-full rounded-3xl border bg-white p-5 text-left shadow-sm hover:shadow"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black text-slate-400">{r.id}</p><h2 className="text-lg font-black">{r.departCity} → {r.arriveeCity}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{r.eligibilityStatus||"—"} · {r.status}</span></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-4"><span>Salaire: <b>{Number(r.salaryApproved||0).toLocaleString()} {r.salaryCurrency||"XAF"}</b></span><span>Coût: <b>{Number(r.costTotal||0).toLocaleString()} {r.salaryCurrency||"XAF"}</b></span><span>Charge: <b>{r.eligibilityBurdenPercent??"—"}%</b></span><span>Seuil: <b>{r.eligibilityThresholdPercent??50}%</b></span></div></button>)}</div>}
{selected&&<div className="fixed inset-0 z-50 bg-black/30 p-5" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="mx-auto mt-10 max-h-[85vh] max-w-2xl overflow-auto rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Dossier Mobility</h2><p className="mt-2 text-sm text-slate-500">{selected.departCity} → {selected.arriveeCity}</p><div className="mt-5 grid gap-3">{Object.entries(selected).map(([k,v])=><div key={k} className="rounded-2xl bg-slate-50 p-3"><span className="text-xs text-slate-400">{k}</span><div className="font-bold break-words">{String(v??"—")}</div></div>)}</div></div></div>}</div></div></main>}
