import type { SupabaseClient } from "@supabase/supabase-js";
export type CEOSeverity="INFO"|"WATCH"|"CRITICAL";
export type CEOAlert={id:string;severity:CEOSeverity;title:string;detail:string;metric:string|null};
export type CEOSnapshot={generatedAt:string;periodDays:number;temporal:{eventCount7d:number;eventCountPrev7d:number;eventDeltaPct:number|null;traceCounts:{observation:number;insight:number;recommendation:number;outcome:number;learning:number};pendingApprovals:number};kpis:{users:number;newUsers7d:number;activeJobs:number;applications7d:number;publishedRecruiterJobs:number;activeSubscriptions:number;revenue30d:number;recurringMonthlyValue:number;commissionsOutstanding:number;partners:number;aiRequests7d:number;aiSuccessRate:number};deltas:{users7dPct:number|null;applications7dPct:number|null;revenue30dPct:number|null};projections:{revenue30d:number;applications30d:number;newUsers30d:number};alerts:CEOAlert[];actions:Array<{id:string;priority:"P1"|"P2"|"P3";title:string;reason:string;kpi:string}>;methodology:string[]};
const pct=(c:number,p:number)=>p===0?(c===0?0:null):Math.round(((c-p)/p)*1000)/10;
const sum=(rows:any[])=>rows.reduce((n,r)=>n+(Number(r.amount)||0),0);
export async function buildCEOIntelligence(sb:SupabaseClient):Promise<CEOSnapshot>{
 const now=Date.now(),d=(n:number)=>new Date(now-n*86400000).toISOString(),since7=d(7),since14=d(14),since30=d(30);
 const [users,users7,users14,activeJobs,publishedRecruiterJobs,apps7,apps14,payments30,payments60,activeSubs,commissions,partners,ai7,event7,event14,traceStages,pendingTraces]=await Promise.all([
  sb.from("User").select("id",{count:"exact",head:true}),sb.from("User").select("id",{count:"exact",head:true}).gte("createdAt",since7),sb.from("User").select("id",{count:"exact",head:true}).gte("createdAt",since14).lt("createdAt",since7),
  sb.from("Job").select("id",{count:"exact",head:true}).eq("isActive",true),sb.from("RecruiterJob").select("id",{count:"exact",head:true}).eq("status","published"),
  sb.from("Application").select("id",{count:"exact",head:true}).gte("createdAt",since7).neq("status","DISCOVERED"),sb.from("Application").select("id",{count:"exact",head:true}).gte("createdAt",since14).lt("createdAt",since7).neq("status","DISCOVERED"),
  sb.from("Payment").select("amount,status").eq("status","PAID").gte("paidAt",since30),sb.from("Payment").select("amount,status").eq("status","PAID").gte("paidAt",new Date(now-60*86400000).toISOString()).lt("paidAt",since30),
  sb.from("Subscription").select("id,priceAmount,billingInterval,status").eq("status","ACTIVE"),sb.from("Commission").select("amount,status").in("status",["GENERATED","PENDING","VALIDATED","PAYABLE"]),
  sb.from("Partner").select("id",{count:"exact",head:true}),sb.from("AiUsage").select("success").gte("createdAt",since7),sb.from("JiaEvent").select("id",{count:"exact",head:true}).gte("occurredAt",since7),sb.from("JiaEvent").select("id",{count:"exact",head:true}).gte("occurredAt",since14).lt("occurredAt",since7),sb.from("JiaIntelligenceTrace").select("stage"),sb.from("JiaIntelligenceTrace").select("id",{count:"exact",head:true}).eq("status","PENDING_APPROVAL")
 ]);
 const errs=[users,users7,users14,activeJobs,publishedRecruiterJobs,apps7,apps14,payments30,payments60,activeSubs,commissions,partners,ai7,event7,event14,traceStages,pendingTraces].map(x=>x.error).filter(Boolean);if(errs.length)throw new Error(errs[0]!.message);
 const newUsers7=users7.count||0,prevUsers7=users14.count||0,applications7=apps7.count||0,prevApplications7=apps14.count||0,revenue30=sum(payments30.data||[]),revenuePrev30=sum(payments60.data||[]),subs=activeSubs.data||[],commissionsOutstanding=sum(commissions.data||[]),aiRows=ai7.data||[],aiSuccessRate=aiRows.length?Math.round(aiRows.filter((r:any)=>r.success===true).length/aiRows.length*1000)/10:100;
 const traceRows=traceStages.data||[],traceCounts={observation:traceRows.filter((r:any)=>r.stage==="OBSERVATION").length,insight:traceRows.filter((r:any)=>r.stage==="INSIGHT").length,recommendation:traceRows.filter((r:any)=>r.stage==="RECOMMENDATION").length,outcome:traceRows.filter((r:any)=>r.stage==="OUTCOME").length,learning:traceRows.filter((r:any)=>r.stage==="LEARNING").length};const eventCount7d=event7.count||0,eventCountPrev7d=event14.count||0,eventDeltaPct=pct(eventCount7d,eventCountPrev7d);
 const recurringMonthlyValue=subs.reduce((n,s)=>n+(Number(s.priceAmount)||0)/(String(s.billingInterval).toLowerCase()==="annual"?12:1),0),alerts:CEOAlert[]=[];if((activeJobs.count||0)<50)alerts.push({id:"offers-low",severity:"WATCH",title:"Réserve d’opportunités basse",detail:"Seulement "+(activeJobs.count||0)+" offres actives sont actuellement disponibles.",metric:"activeJobs"});
 const appDelta=pct(applications7,prevApplications7);if(appDelta!==null&&appDelta<=-20)alerts.push({id:"applications-down",severity:"WATCH",title:"Candidatures en baisse",detail:"Les candidatures des 7 derniers jours sont à "+appDelta+"% par rapport aux 7 jours précédents.",metric:"applications7d"});
 const paymentFailed=await sb.from("Payment").select("id",{count:"exact",head:true}).eq("status","FAILED").gte("createdAt",since30),paymentTotal=await sb.from("Payment").select("id",{count:"exact",head:true}).gte("createdAt",since30);if(paymentFailed.error||paymentTotal.error)throw new Error((paymentFailed.error||paymentTotal.error)!.message);
 const failureRate=(paymentTotal.count||0)>0?(paymentFailed.count||0)/(paymentTotal.count||1)*100:0;if(failureRate>=10)alerts.push({id:"payments-failure",severity:"CRITICAL",title:"Échec de paiement élevé",detail:"Le taux d’échec des paiements sur 30 jours est de "+Math.round(failureRate*10)/10+"%.",metric:"paymentFailureRate"});if(aiRows.length>=10&&aiSuccessRate<95)alerts.push({id:"ai-reliability",severity:"WATCH",title:"Fiabilité J’IA à surveiller",detail:"Le taux de succès des appels J’IA sur 7 jours est de "+aiSuccessRate+"%.",metric:"aiSuccessRate"});
 const actions=[...(alerts.some(a=>a.id==="payments-failure")?[{id:"payment-recovery",priority:"P1" as const,title:"Analyser le tunnel paiement",reason:"Le taux d’échec dépasse le seuil opérationnel.",kpi:"paymentFailureRate"}]:[]),...(alerts.some(a=>a.id==="offers-low")?[{id:"market-supply",priority:"P2" as const,title:"Renforcer la collecte d’opportunités",reason:"La profondeur du marché actif est sous le seuil de surveillance.",kpi:"activeJobs"}]:[]),...(alerts.some(a=>a.id==="applications-down")?[{id:"conversion-review",priority:"P2" as const,title:"Examiner la conversion candidature",reason:"Le volume de candidatures recule sur la période comparable.",kpi:"applications7d"}]:[]),...(alerts.some(a=>a.id==="ai-reliability")?[{id:"ai-reliability",priority:"P2" as const,title:"Auditer la fiabilité J’IA",reason:"Le taux de succès IA est sous 95%.",kpi:"aiSuccessRate"}]:[])];
 const factor=30/7;return{generatedAt:new Date().toISOString(),periodDays:7,temporal:{eventCount7d,eventCountPrev7d,eventDeltaPct,traceCounts,pendingApprovals:pendingTraces.count||0},kpis:{users:users.count||0,newUsers7d:newUsers7,activeJobs:activeJobs.count||0,applications7d:applications7,publishedRecruiterJobs:publishedRecruiterJobs.count||0,activeSubscriptions:subs.length,revenue30d,recurringMonthlyValue:Math.round(recurringMonthlyValue),commissionsOutstanding,partners:partners.count||0,aiRequests7d:aiRows.length,aiSuccessRate},deltas:{users7dPct:pct(newUsers7,prevUsers7),applications7dPct:appDelta,revenue30dPct:pct(revenue30,revenuePrev30)},projections:{revenue30d:Math.round(revenue30d),applications30d:Math.round(applications7*factor),newUsers30d:Math.round(newUsers7*factor)},alerts,actions,methodology:["KPI calculés à partir des données Jobly réelles, sans valeurs de démonstration.","Les projections 30 jours extrapolent le rythme observé sur 7 jours et ne sont pas des prédictions garanties.","La valeur récurrente mensuelle convertit les abonnements annuels en équivalent mensuel.","Les actions sont des recommandations déterministes; aucune décision juridiquement ou financièrement engageante n’est exécutée automatiquement."]};
}