export type PublicationExtraction = { value:string|null; method:"jsonld"|"meta"|"text"|"none" };
function iso(value:string|null|undefined):string|null{if(!value)return null;const d=new Date(String(value));return Number.isFinite(d.getTime())?d.toISOString():null;}
function cleanText(value:string):string{return String(value||"").replace(/<script\\b[^>]*>[\\s\\S]*?<\\/script>/gi," ").replace(/<style\\b[^>]*>[\\s\\S]*?<\\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/\\s+/g," ").trim();}
function jsonLd(html:string):string|null{const re=/<script\\b[^>]*type=[\"']application\\/ld\\+json[\"'][^>]*>([\\s\\S]*?)<\\/script>/gi;let m;while((m=re.exec(html))){try{const p=JSON.parse(m[1]);const xs=Array.isArray(p)?p:[p];const walk=(x:any):string|null=>{if(!x||typeof x!=="object")return null;const t=x["@type"];if(t==="JobPosting"||(Array.isArray(t)&&t.includes("JobPosting")))return iso(x.datePosted||x.datePublished||x.dateModified);if(Array.isArray(x["@graph"]))for(const y of x["@graph"]){const v=walk(y);if(v)return v;}return null;};for(const x of xs){const v=walk(x);if(v)return v;}}catch{}}return null;}
function meta(html:string,names:string[]):string|null{const tag=html.match(/<meta\\b[^>]+>/gi)||[];for(const t of tag){const n=t.match(/(?:name|property)=[\"']([^\"']+)[\"']/i)?.[1]?.toLowerCase();const c=t.match(/content=[\"']([^\"']+)[\"']/i)?.[1];if(n&&c&&names.some(x=>x.toLowerCase()===n))return iso(c);}return null;}
const P:Record<string,RegExp[]>={infosconcourseducation:[/publication\\s*[:\\-]\\s*([0-9]{1,2}\\s+[A-Za-zÀ-ÿ]+\\s+20[0-9]{2})/i,/publi[ée]\\s+le\\s*[:\\-]?\\s*([0-9]{1,2}\\s+[A-Za-zÀ-ÿ]+\\s+20[0-9]{2})/i],jobinfocamer:[/([0-9]{1,2}\\s+(?:janvier|f[ée]vrier|mars|avril|mai|juin|juillet|ao[uû]t|septembre|octobre|novembre|d[ée]cembre)\\s+20[0-9]{2})\\s+[^\\n]{0,80}(?:Nouveau|CDD|CDI|STAGE)/i],emplois_cameroun:[/([0-9]{1,2}\\/[0-9]{1,2}\\/20[0-9]{2})/i],jobincamer:[/(?:publi[ée]|post[ée]|date(?:\\s+de)?\\s+publication)\\s*[:\\-]?\\s*([0-9]{1,2}[\\/\\-][0-9]{1,2}[\\/\\-]20[0-9]{2})/i],jobivoire_ci:[/(?:date(?:\\s+de)?\\s+publication|publi[ée]|post[ée])\\s*[:\\-]?\\s*([0-9]{1,2}[\\/\\-][0-9]{1,2}[\\/\\-]20[0-9]{2})/i],ajirika_east:[/(?:date\\s+posted|posted\\s+on|date\\s+published)\\s*[:\\-]?\\s*([A-Za-z]+\\s+[0-9]{1,2},?\\s+20[0-9]{2})/i],brightermonday_ke:[/(?:posted\\s+on|date\\s+opened|date\\s+posted)\\s*[:\\-]?\\s*([0-9]{1,2}\\/[0-9]{1,2}\\/20[0-9]{2})/i],unjobnet:[/(?:date\\s+posted|posted)\\s*[:\\-]?\\s*([0-9]{1,2}[\\/\\-][0-9]{1,2}[\\/\\-]20[0-9]{2})/i],goafricajobs:[/(?:date\\s+posted|published|publi[ée])\\s*[:\\-]?\\s*([0-9]{1,2}[\\/\\-][0-9]{1,2}[\\/\\-]20[0-9]{2})/i],ajar_cd:[/(?:date\\s+publication|publi[ée]|posted)\\s*[:\\-]?\\s*([0-9]{1,2}[\\/\\-][0-9]{1,2}[\\/\\-]20[0-9]{2})/i]};
const M:Record<string,string>={janvier:"01",février:"02",fevrier:"02",mars:"03",avril:"04",mai:"05",juin:"06",juillet:"07",août:"08",aout:"08",septembre:"09",octobre:"10",novembre:"11",décembre:"12",decembre:"12"};
function parseDate(s:string):string|null{let m=s.trim().match(/^(\\d{1,2})[\\/\\-](\\d{1,2})[\\/\\-](20\\d{2})$/);if(m)return new Date(Date.UTC(+m[3],+m[2]-1,+m[1])).toISOString();m=s.trim().match(/^(\\d{1,2})\\s+([A-Za-zÀ-ÿ]+)\\s+(20\\d{2})$/);if(m&&M[m[2].toLowerCase()])return new Date(Date.UTC(+m[3],+M[m[2].toLowerCase()]-1,+m[1])).toISOString();m=s.trim().match(/^([A-Za-z]+)\\s+(\\d{1,2}),?\\s+(20\\d{2})$/);if(m){const d=new Date(m[1]+" "+m[2]+", "+m[3]);return Number.isFinite(d.getTime())?d.toISOString():null;}return null;}
export function extractSourcePublishedAt(html:string,url:string,sourceKey:string):string|null{const ld=jsonLd(html);if(ld)return ld;const mm=meta(html,["article:published_time","datePublished","date","DC.date","publishdate","dateposted"]);if(mm)return mm;for(const re of P[sourceKey]||[]){const m=cleanText(html).match(re);const d=parseDate(m?.[1]||"");if(d)return d;}return null;}
export function resolveEffectivePublicationDate(input:{sourcePublishedAt:string|null;firstHarvestAt:string|null;createdAt:string;deadline:string|null;now?:string}){const now=new Date(input.now||new Date().toISOString());const real=iso(input.sourcePublishedAt);const fallback=real?null:(iso(input.firstHarvestAt)||iso(input.createdAt));const effective=real||fallback;const t=effective?new Date(effective).getTime():NaN;const dl=input.deadline?new Date(input.deadline).getTime():NaN;return {effectivePublishedAt:effective,publicationDateEstimated:Boolean(!real&&fallback),visible:Number.isFinite(t)&&t>=now.getTime()-30*86400000&&(!Number.isFinite(dl)||dl>=now.getTime())};}
