"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import BottomNav, { PARTNER_NAV } from "../../../components/BottomNav";
import PageHeader from "../../../components/PageHeader";
import { getSupabaseClient } from "../../../lib/supabase";

export default function PartnerProfile() {
  const router = useRouter();
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  const [code,setCode]=useState(""); const [provider,setProvider]=useState("MTN_MOMO"); const [phone,setPhone]=useState(""); const [kyc,setKyc]=useState("PENDING");
  useEffect(()=>{(async()=>{const s=await getSupabaseClient().auth.getSession(); if(!s.data.session){router.replace("/");return;} const r=await fetch("/api/partner/profile",{headers:{Authorization:`Bearer ${s.data.session.access_token}`}}); const b=await r.json().catch(()=>({})); if(!r.ok){setMessage(b.message||"Profil indisponible.");} else {const p=b.partner||{};setCode(p.referralCode||"");setProvider(p.payoutProvider||"MTN_MOMO");setPhone(p.payoutPhone||"");setKyc(p.kycStatus||"PENDING");} setLoading(false);})()},[router]);
  async function save(){const s=await getSupabaseClient().auth.getSession(); if(!s.data.session)return; setSaving(true);setMessage(""); try{const r=await fetch("/api/partner/profile",{method:"PUT",headers:{Authorization:`Bearer ${s.data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({payoutProvider:provider,payoutPhone:phone})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"Enregistrement impossible.");setMessage("Profil enregistré ✓");}catch(e){setMessage(e instanceof Error?e.message:"Erreur.")}finally{setSaving(false)}}
  if(loading)return <main className="grid min-h-[100dvh] place-items-center bg-white font-bold text-navy">Chargement…</main>;
  return <main className="relative min-h-[100dvh] bg-white pb-28 text-navy"><PageHeader label="Mon profil partenaire" eyebrow="PARTNER" onBack={()=>router.push("/partner")} /><div className="mx-auto max-w-3xl space-y-4 px-5 py-6"><h1 className="font-heading text-2xl font-extrabold">Profil partenaire</h1><section className="rounded-[20px] border border-slate-100 bg-white p-5 shadow-card space-y-4"><div><span className="text-xs font-bold text-jobly-gray">Code de parrainage</span><p className="mt-1 rounded-xl bg-slate-50 px-4 py-3 font-black">{code||"—"}</p></div><div><span className="text-xs font-bold text-jobly-gray">Statut KYC</span><p className="mt-1 font-extrabold">{kyc}</p></div><label className="block text-sm font-extrabold">Opérateur<select value={provider} onChange={e=>setProvider(e.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3"><option value="MTN_MOMO">MTN MoMo</option><option value="ORANGE_MONEY">Orange Money</option></select></label><label className="block text-sm font-extrabold">Numéro de paiement<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3" placeholder="+237 6 XX XX XX XX" /></label><button onClick={()=>router.push("/partner/settings")} className="w-full rounded-2xl border border-slate-200 py-3 font-extrabold">Paramètres partenaire</button><button onClick={save} disabled={saving||!phone.trim()} className="w-full rounded-2xl bg-jobly-yellow py-3 font-extrabold disabled:opacity-50">{saving?"Enregistrement…":"Enregistrer"}</button>{message&&<p className="text-sm font-bold text-jobly-blue">{message}</p>}</section></div><BottomNav active="/partner/profile" items={PARTNER_NAV}/></main>;
}
