"use client";
import {useEffect,useState} from "react";
import AppShell from "@/components/ui/AppShell";
import {Button,Card,EmptyState,LoadingState,PageIntro,Section} from "@/components/ui";
export default function RecruiterTests(){const[tests,setTests]=useState<any[]>([]),[recruitments,setRecruitments]=useState<string[]>([]),[rid,setRid]=useState(""),[title,setTitle]=useState("Test de sélection"),[duration,setDuration]=useState(1800),[state,setState]=useState("loading"),[error,setError]=useState("");
async function load(){setState("loading");try{const r=await fetch("/api/recruitment360/tests");const d=await r.json();if(!r.ok)throw new Error(d.message);setTests(d.tests??[]);setRecruitments(d.recruitments??[]);if(!rid&&d.recruitments?.[0])setRid(d.recruitments[0]);setState("ready")}catch(e){setError(e instanceof Error?e.message:"Erreur");setState("ready")}}
useEffect(()=>{void load()},[]);
async function create(){setError("");const r=await fetch("/api/recruitment360/tests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",recruitmentId:rid,title,durationSeconds:duration,maxAttempts:1})});const d=await r.json();if(!r.ok){setError(d.message||"Création impossible");return}await load()}
return <AppShell role="recruiter" active="/recruiter/tests" title="Tests 360°" eyebrow="RECRUTEMENT 360°" initial="T" width="lg"><PageIntro eyebrow="LOT 4" title="Tests" subtitle="Sessions chronométrées par l'heure serveur, sauvegarde, surveillance et reprise."/><Section title="Créer un test"><Card><div className="grid gap-3 sm:grid-cols-4"><select className="rounded-xl border p-3" value={rid} onChange={e=>setRid(e.target.value)}><option value="">Recrutement…</option>{recruitments.map(id=><option key={id} value={id}>{id}</option>)}</select><input className="rounded-xl border p-3" value={title} onChange={e=>setTitle(e.target.value)}/><input className="rounded-xl border p-3" type="number" min={60} value={duration} onChange={e=>setDuration(Number(e.target.value))}/><Button onClick={()=>void create()} disabled={!rid}>Créer</Button></div>{error&&<p className="mt-3 text-sm font-bold text-red-600">{error}</p>}</Card></Section>{state==="loading"?<LoadingState/>:tests.length?<div className="space-y-3">{tests.map(t=><Card key={t.id}><b>{t.title}</b><p className="text-sm text-muted">{t.durationSeconds}s · {t.status} · {(t.RecruitmentTestQuestion??[]).length} question(s)</p></Card>) :<EmptyState title="Aucun test créé pour les recrutements accessibles."/>}</AppShell>}
