import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { adminClient, ensureUser, getAuthUser } from "../../../lib/server-auth";
import { getIdempotentResult, saveIdempotentResult } from "../../../lib/idempotency";
import { getPlan, getPrice, type BillingInterval, type PlanCode } from "../../../lib/billingCatalog";
import { getProvider } from "../../../lib/paymentProviders";
const err=(message:string,status:number,code=message)=>NextResponse.json({error:code,message},{status});
export async function GET(request: NextRequest){try{const auth=await getAuthUser(request);if(!auth)return err("Session requise.",401,"UNAUTHENTICATED");const sb=adminClient(),u=await ensureUser(sb,auth),q=request.nextUrl.searchParams;const page=Math.max(1,Number(q.get("page")||1)),limit=Math.min(50,Math.max(1,Number(q.get("limit")||20))),status=q.get("status");let query=sb.from("Payment").select("*",{count:"exact"}).eq("userId",u.id).order("createdAt",{ascending:false}).range((page-1)*limit,page*limit-1);if(status)query=query.eq("status",status);const {data,error,count}=await query;if(error)throw new Error(error.message);return NextResponse.json({payments:data||[],page,limit,total:count||0});}catch(e){return err(e instanceof Error?e.message:"Historique indisponible.",500);}}
export async function POST(request: NextRequest){try{const auth=await getAuthUser(request);if(!auth)return err("Session requise.",401,"UNAUTHENTICATED");const body=await request.json(),sb=adminClient(),u=await ensureUser(sb,auth),idem=await getIdempotentResult(request,"/api/payments",u.id,body);if("error"in idem)return err("Clé d'idempotence manquante ou réutilisée avec un payload différent.",idem.conflict?409:400,idem.error);if(idem.existing)return NextResponse.json(idem.existing.response,{status:idem.existing.statusCode});const subscriptionId=String(body.subscriptionId||"");const {data:sub,error:subError}=await sb.from("Subscription").select("*").eq("id",subscriptionId).eq("userId",u.id).maybeSingle();if(subError)throw new Error(subError.message);if(!sub)return err("Abonnement introuvable.",404,"SUBSCRIPTION_NOT_FOUND");const plan=getPlan(String(sub.planCode));if(!plan)return err("Plan invalide.",400,"INVALID_PLAN");const interval=String(body.interval||sub.billingInterval||"").toUpperCase() as BillingInterval;if(interval!=="MONTHLY"&&interval!=="ANNUAL")return err("Intervalle invalide.",400,"INVALID_INTERVAL");const providerName=String(body.provider||sub.provider||"MOCK").toUpperCase();const amount=getPrice(plan.code as PlanCode,interval);if(Number(body.amount)!==amount||String(body.currency||"XAF").toUpperCase()!=="XAF")return err("Le montant ou la devise ne correspond pas au catalogue serveur.",422,"INVALID_AMOUNT");const id=crypto.randomUUID(),now=new Date().toISOString();const {data:payment,error}=await sb.from("Payment").insert({id,userId:u.id,subscriptionId,provider:providerName,externalId:id,amount,currency:"XAF",status:"CREATED",idempotencyKey:idem.key,createdAt:now,updatedAt:now}).select("*").single();if(error)throw new Error(error.message);const intent=await getProvider(providerName).createPayment({paymentId:id,amount,currency:"XAF",phone:auth.phone});const response={payment:{...payment,checkoutReference:intent.checkoutReference},instructions:intent.instructions};await saveIdempotentResult(u.id,"/api/payments",idem.key,idem.hash,201,response);return NextResponse.json(response,{status:201});}catch(e){return err(e instanceof Error?e.message:"Création du paiement impossible.",500);}}
