"use client";
import {useEffect,useMemo,useState} from "react";
import AppShell from "@/components/ui/AppShell";
import {Button,Card,EmptyState,ErrorState,LoadingState,PageIntro,Section} from "@/components/ui";
import {getSupabaseClient} from "@/lib/supabase";

type Candidate={applicationId:string;candidateName:string;jobTitle:string;companyName:string;candidateState:string;decision:any;salaryExpectation:number|null;salaryCurrency:string};
const copy={fr:{title:"Décisions",sub:"Décision finale, recommandation J’IA explicable, offre et négociation.",candidate:"Candidat",outcome:"Issue",offer:"Offre",pool:"Vivier",reject:"Rejet",rationale:"Justification",score:"Score global /100",save:"Finaliser",vote:"Avis jury",yes:"Favorable",reserve:"Réserve",no:"Défavorable",recommend:"Analyser avec J’IA",policy:"Politique de décision",weights:"Pondération CV / test / entretien",twoStep:"Validation RH puis DG",references:"Références obligatoires",salaryMin:"Salaire min",salaryMax:"Salaire max",savePolicy:"Enregistrer la politique",offerSend:"Envoyer l’offre",salary:"Salaire proposé",deadline:"Date limite de réponse",channel:"Canal",message:"Message",jobly:"Jobly",email:"Email",whatsapp:"WhatsApp",call:"Appel",empty:"Aucune candidature au stade décision.",error:"Erreur",reference:"Références",status:"Statut"},en:{title:"Decisions",sub:"Final decision, explainable J’IA recommendation, offer and negotiation.",candidate:"Candidate",outcome:"Outcome",offer:"Offer",pool:"Reserve",reject:"Reject",rationale:"Rationale",score:"Overall score /100",save:"Finalize",vote:"Jury opinion",yes:"Favorable",reserve:"Reserve",no:"Unfavorable",recommend:"Analyse with J’IA",policy:"Decision policy",weights:"CV / test / interview weighting",twoStep:"HR then DG approval",references:"References required",salaryMin:"Salary min",salaryMax:"Salary max",savePolicy:"Save policy",offerSend:"Send offer",salary:"Proposed salary",deadline:"Response deadline",channel:"Channel",message:"Message",jobly:"Jobly",email:"Email",whatsapp:"WhatsApp",call:"Call",empty:"No candidate at decision stage.",error:"Error",reference:"References",status:"Status"}};
export default function RecruiterDecisionsPage(){
 const [lang,setLang]=useState<"fr"|"en">("fr"),t=copy[lang], [state,setState]=useState<"loading"|"ready"|"error">("loading"),[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState(""),[error,setError]=useState(""),[form,setForm]=useState({outcome:"OFFER",rationale:"",score:"",nextAction:"PREPARE_OFFER"}),[policy,setPolicy]=useState({recruitmentId:"",cv:.35,test:.30,interview:.35,twoStep:false,references:false,min:"",max:"",currency:"XAF"}),[offer,setOffer]=useState<any>(null),[offerForm,setOfferForm]=useState({salary:"",deadline:"",channel:"JOBLY",message:""}),[jia,setJia]=useState<any>(null);
 useEffect(()=>{setLang((document.documentElement.lang||"fr").toLowerCase().startsWith("en")?"en":"fr")},[]);
 async function headers(){const {data:{session}}=await getSupabaseClient().auth.getSession();if(!session)throw new Error("Session requise.");return{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"}}
 async function load(){setState("loading");try{const h=await headers();const r=await fetch("/api/recruitment360/decisions",{headers:h});const d=await r.json();if(!r.ok)throw new Error(d.message);setCandidates(d.candidates||[]);if(!selected&&d.candidates?.[0])setSelected(d.candidates[0].applicationId);setState("ready")}catch(e){setError(e instanceof Error?e.message:"Erreur");setState("error")}}
 useEffect(()=>{void load()},[]);
 const current=useMemo(()=>candidates.find(c=>c.applicationId===selected)||null,[candidates,selected]);
 async function workspace(id:string){const h=await headers();const r=await fetch("/api/recruitment360/decisions?applicationId="+encodeURIComponent(id),{headers:h});const d=await r.json();if(!r.ok)throw new Error(d.message);return d.workspace}
 useEffect(()=>{if(!current)return;void workspace(current.applicationId).then(w=>{setOffer(w?.offer||null);if(w?.policy)setPolicy(p=>({...p,recruitmentId:w.recruitment.id,cv:Number(w.policy.cvWeight),test:Number(w.policy.testWeight),interview:Number(w.policy.interviewWeight),twoStep:Boolean(w.policy.requireTwoStepApproval),references:Boolean(w.policy.requireReferences),min:w.policy.salaryMin??"",max:w.policy.salaryMax??"",currency:w.policy.salaryCurrency||"XAF"}))}).catch(e=>setError(e instanceof Error?e.message:"Erreur"))},[current?.applicationId]);
 async function post(body:any){const h=await headers();const r=await fetch("/api/recruitment360/decisions",{method:"POST",headers:h,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Erreur");return d}
 async function finalize(e:any){e.preventDefault();try{await post({action:"finalize",applicationId:selected,outcome:form.outcome,rationale:form.rationale,scoreTotal:form.score===""?null:Number(form.score),nextAction:form.nextAction});await load();const w=await workspace(selected);setOffer(w.offer||null);setError("")}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 async function savePolicy(e:any){e.preventDefault();try{if(!current)throw new Error("Candidature requise");await post({action:"policy",recruitmentId:policy.recruitmentId,cvWeight:policy.cv,testWeight:policy.test,interviewWeight:policy.interview,twoStep:policy.twoStep,requireReferences:policy.references,salaryMin:policy.min,salaryMax:policy.max,currency:policy.currency});setError("")}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 async function sendOffer(e:any){e.preventDefault();try{await post({action:"sendOffer",offerId:offer.id,salary:Number(offerForm.salary),deadline:new Date(offerForm.deadline).toISOString(),channel:offerForm.channel,message:offerForm.message});const w=await workspace(selected);setOffer(w.offer);setError("")}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 async function recommend(){try{const d=await post({action:"recommendation",applicationId:selected});setJia(d.recommendation)}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 return <AppShell role="recruiter" active="/recruiter/decisions" title={t.title} eyebrow="RECRUTEMENT 360°" initial="J" width="lg">
  <PageIntro eyebrow="LOT 6" title={t.title} subtitle={t.sub}/>
  {error&&<p className="mt-3 rounded-xl border p-3 text-sm">{error}</p>}
  {state==="loading"&&<LoadingState/>}{state==="error"&&<ErrorState title={error||t.error} onRetry={load}/>}
  {state==="ready"&&<>{candidates.length===0?<EmptyState title={t.empty}/>:<>
   <Section title={t.candidate}><Card><select value={selected} onChange={e=>setSelected(e.target.value)} className="w-full rounded-xl border p-3">{candidates.map(c=><option key={c.applicationId} value={c.applicationId}>{c.candidateName} · {c.jobTitle} · {c.candidateState}</option>)}</select></Card></Section>
   {current&&<Section title={t.title}><Card><div className="grid gap-3 sm:grid-cols-2">
    <p className="text-sm"><strong>{current.candidateName}</strong><br/>{current.jobTitle} · {current.companyName}<br/>{t.status}: {current.candidateState}</p>
    <Button type="button" onClick={()=>void recommend()}>{t.recommend}</Button>
   </div>{jia&&<div className="mt-3 rounded-xl border p-3 text-sm"><strong>J’IA</strong><p className="mt-1">{jia.rationale}</p><p className="mt-2 text-xs opacity-70">{jia.provider} · {jia.confidence}</p></div>}
   <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={()=>void post({action:"vote",applicationId:selected,recommendation:"YES"})}>{t.yes}</Button><Button size="sm" variant="ghost" onClick={()=>void post({action:"vote",applicationId:selected,recommendation:"RESERVE"})}>{t.reserve}</Button><Button size="sm" variant="ghost" onClick={()=>void post({action:"vote",applicationId:selected,recommendation:"NO"})}>{t.no}</Button></div></Card></Section>}
   <Section title={t.policy}><Card><form onSubmit={savePolicy} className="grid gap-3 sm:grid-cols-3">
    <label className="text-sm">{t.weights} — CV<input type="number" step="0.01" min="0" max="1" value={policy.cv} onChange={e=>setPolicy(p=>({...p,cv:Number(e.target.value)}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <label className="text-sm">Test<input type="number" step="0.01" min="0" max="1" value={policy.test} onChange={e=>setPolicy(p=>({...p,test:Number(e.target.value)}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <label className="text-sm">Entretien<input type="number" step="0.01" min="0" max="1" value={policy.interview} onChange={e=>setPolicy(p=>({...p,interview:Number(e.target.value)}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <label className="text-sm"><input type="checkbox" checked={policy.twoStep} onChange={e=>setPolicy(p=>({...p,twoStep:e.target.checked}))}/> {t.twoStep}</label>
    <label className="text-sm"><input type="checkbox" checked={policy.references} onChange={e=>setPolicy(p=>({...p,references:e.target.checked}))}/> {t.references}</label>
    <label className="text-sm">{t.salaryMin}<input type="number" value={policy.min} onChange={e=>setPolicy(p=>({...p,min:e.target.value}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <label className="text-sm">{t.salaryMax}<input type="number" value={policy.max} onChange={e=>setPolicy(p=>({...p,max:e.target.value}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <label className="text-sm">Devise<input value={policy.currency} onChange={e=>setPolicy(p=>({...p,currency:e.target.value}))} className="mt-1 w-full rounded-xl border p-3"/></label>
    <Button type="submit" className="sm:col-span-3">{t.savePolicy}</Button>
   </form></Card></Section>
   <Section title={t.title}><Card><form onSubmit={finalize} className="grid gap-3">
    <select value={form.outcome} onChange={e=>setForm(f=>({...f,outcome:e.target.value}))} className="rounded-xl border p-3"><option value="OFFER">{t.offer}</option><option value="POOL">{t.pool}</option><option value="REJECTED">{t.reject}</option></select>
    <input type="number" min="0" max="100" value={form.score} onChange={e=>setForm(f=>({...f,score:e.target.value}))} placeholder={t.score} className="rounded-xl border p-3"/>
    <textarea required minLength={5} value={form.rationale} onChange={e=>setForm(f=>({...f,rationale:e.target.value}))} placeholder={t.rationale} className="min-h-28 rounded-xl border p-3"/>
    <Button type="submit">{t.save}</Button>
   </form></Card></Section>
   {offer&&<Section title={t.offer}><Card><p className="text-sm mb-3">{offer.status} · {offer.salaryProposed} {offer.salaryCurrency}</p>{offer.status==="DRAFT"&&<form onSubmit={sendOffer} className="grid gap-3"><input required type="number" min={offer.salaryMin??0} max={offer.salaryMax??undefined} value={offerForm.salary} onChange={e=>setOfferForm(f=>({...f,salary:e.target.value}))} placeholder={t.salary} className="rounded-xl border p-3"/><input required type="datetime-local" value={offerForm.deadline} onChange={e=>setOfferForm(f=>({...f,deadline:e.target.value}))} className="rounded-xl border p-3"/><select value={offerForm.channel} onChange={e=>setOfferForm(f=>({...f,channel:e.target.value}))} className="rounded-xl border p-3"><option value="JOBLY">{t.jobly}</option><option value="EMAIL">{t.email}</option><option value="WHATSAPP">{t.whatsapp}</option><option value="CALL">{t.call}</option></select><textarea value={offerForm.message} onChange={e=>setOfferForm(f=>({...f,message:e.target.value}))} placeholder={t.message} className="min-h-24 rounded-xl border p-3"/><Button type="submit">{t.offerSend}</Button></form>}</Card></Section>}
  </>}</>}
 </AppShell>
}
