"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import AppShell from "@/components/ui/AppShell";
import {Button,Card,EmptyState,ErrorState,LoadingState,PageIntro,Section} from "@/components/ui";
import {getSupabaseClient} from "@/lib/supabase";

type Report={id:string;reportType:string;title:string;summary:string;metrics:any;generatedAt:string};
type Review={id:string;applicationId:string;recommendation:string;reviewText:string;visibleToCandidate:boolean;createdAt:string};
export default function RecruiterReportsPage(){
 const router=useRouter();const[state,setState]=useState("loading");const[reports,setReports]=useState<Report[]>([]);const[reviews,setReviews]=useState<Review[]>([]);const[error,setError]=useState("");
 const[recruitmentId,setRecruitmentId]=useState("");const[applicationId,setApplicationId]=useState("");const[recommendation,setRecommendation]=useState("RECOMMEND");const[reviewText,setReviewText]=useState("");const[visible,setVisible]=useState(false);
 async function authHeaders(){const{data:{session}}=await getSupabaseClient().auth.getSession();if(!session){router.replace("/");return{};}return{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"}}
 async function load(){setState("loading");try{const h=await authHeaders();const r=await fetch("/api/recruitment360/reports?recruitmentId="+encodeURIComponent(recruitmentId),{headers:h});const d=await r.json();if(!r.ok)throw new Error(d.message||"Chargement impossible");setReports(d.reports??[]);setReviews(d.reviews??[]);setState("ready")}catch(e){setError(e instanceof Error?e.message:"Erreur");setState("error")}}
 async function createReport(type:string){try{const h=await authHeaders();const r=await fetch("/api/recruitment360/reports",{method:"POST",headers:h,body:JSON.stringify({action:"report",recruitmentId,reportType:type,applicationId:applicationId||null})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Rapport impossible");setReports(x=>[d.report,...x])}catch(e){setError(e instanceof Error?e.message:"Rapport impossible")}}
 async function submitReview(e:any){e.preventDefault();try{const h=await authHeaders();const r=await fetch("/api/recruitment360/reports",{method:"POST",headers:h,body:JSON.stringify({action:"review",recruitmentId,applicationId,recommendation,reviewText,visibleToCandidate:visible})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Avis impossible");setReviews(x=>[d.review,...x]);setReviewText("")}catch(e){setError(e instanceof Error?e.message:"Avis impossible")}}
 useEffect(()=>{if(recruitmentId)void load();else setState("ready")},[recruitmentId]);
 return <AppShell role="recruiter" active="/recruiter/reports" title="Rapports & avis" eyebrow="RECRUTEMENT 360°" initial="J" width="lg">
  <PageIntro eyebrow="LOT 7" title="Rapports & avis" subtitle="Synthèse du recrutement, traçabilité et avis structurés." actions={<Button href="/recruiter">Tableau de bord</Button>}/>
  <Card><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Recrutement ID<input value={recruitmentId} onChange={e=>setRecruitmentId(e.target.value)} placeholder="UUID du recrutement" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Candidature ID<input value={applicationId} onChange={e=>setApplicationId(e.target.value)} placeholder="UUID pour rapport candidat/avis" className="mt-1 w-full rounded-xl border p-3"/></label><div className="flex flex-wrap items-end gap-2"><Button onClick={()=>void createReport("RECRUITMENT")}>Rapport recrutement</Button><Button variant="ghost" onClick={()=>void createReport(applicationId?"CANDIDATE":"RECRUITMENT")}>Rapport candidat</Button></div></div></Card>
  {error&&<p className="mt-3 rounded-xl border p-3 text-sm">{error}</p>}
  {state==="loading"&&<LoadingState/>}{state==="error"&&<ErrorState title={error||"Erreur"} onRetry={load}/>}
  {state==="ready"&&recruitmentId&&<>
   <Section title="Rapports">{reports.length===0?<EmptyState title="Aucun rapport généré"/>:<div className="space-y-3">{reports.map(r=><Card key={r.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold">{r.reportType}</p><h2 className="font-black">{r.title}</h2><p className="mt-1 text-sm text-muted">{r.summary}</p></div><time className="text-xs text-muted">{new Date(r.generatedAt).toLocaleString("fr-FR")}</time></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-5">{Object.entries(r.metrics||{}).slice(0,5).map(([k,v])=><div key={k} className="rounded-lg border p-2"><span className="block text-xs text-muted">{k}</span><strong>{String(v??"—")}</strong></div>)}</div></Card>)}</div>}</Section>
   <Section title="Avis"><Card><form onSubmit={submitReview} className="grid gap-3"><label className="text-sm font-bold">Candidature ID<input required value={applicationId} onChange={e=>setApplicationId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Recommandation<select value={recommendation} onChange={e=>setRecommendation(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="STRONG_RECOMMEND">Recommandation forte</option><option value="RECOMMEND">Recommandation</option><option value="RESERVE">Réserve</option><option value="DO_NOT_RECOMMEND">Ne pas recommander</option></select></label><label className="text-sm font-bold">Avis<textarea required minLength={10} value={reviewText} onChange={e=>setReviewText(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border p-3"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Rendre cet avis visible au candidat</label><Button type="submit">Enregistrer l'avis</Button></form></Card>
    {reviews.map(v=><Card key={v.id}><p className="text-xs font-bold">{v.recommendation} · {v.applicationId}</p><p className="mt-1 text-sm">{v.reviewText}</p><p className="mt-1 text-xs text-muted">{v.visibleToCandidate?"Visible au candidat":"Interne"}</p></Card>)}
   </Section>
  </>}
 </AppShell>
}