import { NextRequest, NextResponse } from "next/server";
import { adminClient, ensureUser, getAuthUser } from "../../../lib/server-auth";

const MAX_OFFER_AGE_DAYS = 60;
const DEFAULT_FEED_SIZE = 200;
const MAX_FEED_SIZE = 200;

type Profile = { targetRoles: string[] | null; targetCities: string[] | null; contractPreferences: string[] | null; remotePreference: string | null; preferredSectors?: string[] | null };
type Experience = { startDate: string };
type Job = { id:string; title:string; description:string; location:string|null; contractType:string|null; remoteMode:string|null; minExperienceYears:number|null; isActive:boolean; createdAt:string; companyId:string|null; source:string|null; sourceUrl:string|null; deadline:string|null; lastSeenAt:string|null; sourcePublishedAt:string|null; applicationReady:boolean; applicationProfile:Record<string,unknown>; visualUrl:string|null; visualSource:string|null; applicationCheckedAt:string|null; aiSector?:string|null; aiSkills?:unknown };
type Company = { id:string; name:string; logoUrl:string|null; description:string|null; website:string|null; verified:boolean };
type RecruiterJobRow = { id:string; title:string; companyName:string; description:string; location:string|null; contract:string|null; remoteMode:string|null; minExperienceYears:number|null; status:string; createdAt:string; sourceType:string; sourceUrl:string|null; sourcePlatform:string|null; applicationReady:boolean; applicationProfile:Record<string,unknown>; visualUrl:string|null; visualSource:string|null; applicationCheckedAt:string|null; sector?:string|null; tags?:string[] };
type MatchableJob = { title:string; location:string|null; contractType:string|null; remoteMode:string|null; minExperienceYears:number|null; sector?:string|null; tags?:string[] };

function computeYearsExperience(experiences:Experience[]):number { if(!experiences.length)return 0; const earliest=experiences.map(e=>new Date(e.startDate).getTime()).filter(t=>!Number.isNaN(t)).sort((a,b)=>a-b)[0]; if(earliest===undefined)return 0; return Math.max(0,Math.floor((Date.now()-earliest)/(1000*60*60*24*365))); }
function normalize(value:string|null|undefined):string { return (value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""); }
function addMonths(date:Date, months:number):Date { const copy=new Date(date); const originalDay=copy.getDate(); copy.setDate(1); copy.setMonth(copy.getMonth()+months); const lastDay=new Date(copy.getFullYear(),copy.getMonth()+1,0).getDate(); copy.setDate(Math.min(originalDay,lastDay)); return copy; }
function expirationFor(publishedAt:string|null|undefined, deadline:string|null|undefined, createdAt:string):Date { if(deadline){const d=new Date(deadline);if(Number.isFinite(d.getTime()))return d;} const base=new Date(publishedAt||createdAt); return Number.isFinite(base.getTime())?addMonths(base,2):new Date(0); }
function isFresh(publishedAt:string|null|undefined, deadline:string|null|undefined, createdAt:string):boolean { return expirationFor(publishedAt,deadline,createdAt).getTime()>=Date.now() && (deadline ? true : Date.now()-new Date(publishedAt||createdAt).getTime()<=MAX_OFFER_AGE_DAYS*24*60*60*1000); }
function computeMatch(profile:Profile,yearsExperience:number,job:MatchableJob){ const roles=(profile.targetRoles||[]).map(normalize).filter(Boolean),cities=(profile.targetCities||[]).map(normalize).filter(Boolean),contracts=(profile.contractPreferences||[]).map(normalize).filter(Boolean),sectors=(profile.preferredSectors||[]).map(normalize).filter(Boolean),remote=normalize(profile.remotePreference)||"indifferent",title=normalize(job.title),location=normalize(job.location),contract=normalize(job.contractType),jobRemote=normalize(job.remoteMode)||"no",sector=normalize(job.sector),min=job.minExperienceYears??0; const role=roles.length>0&&roles.some(r=>title.includes(r))?1:0; const city=cities.length>0&&location?(cities.some(c=>location.includes(c))?1:0):0; const contractScore=contracts.length>0&&contract?(contracts.includes(contract)?1:0):0; const sectorScore=sectors.length>0&&sector?(sectors.some(s=>sector.includes(s))?1:0):0; let remoteScore=0;if(remote==="indifferent"||remote===jobRemote)remoteScore=1;else if(remote==="yes"&&jobRemote==="partial")remoteScore=.5;const experience=yearsExperience>=min?1:0; const raw=(role+city+contractScore+sectorScore+remoteScore+experience)/6;return{matchPercent:Math.round(raw*100),breakdown:{role,city,contract:contractScore,sector:sectorScore,remote:remoteScore,experience}}; }

export async function GET(request:NextRequest){
 try{
  const authUser=await getAuthUser(request);if(!authUser)return NextResponse.json({message:"Session requise."},{status:401});
  const supabase=adminClient();const user=await ensureUser(supabase,authUser);const {searchParams}=new URL(request.url);
  const filterContract=searchParams.get("contractType"),filterCity=searchParams.get("city"),filterRemote=searchParams.get("remote"),search=searchParams.get("q");
  const requestedSize=Number(searchParams.get("limit")||DEFAULT_FEED_SIZE);const limit=Math.min(Math.max(Number.isFinite(requestedSize)?requestedSize:DEFAULT_FEED_SIZE,1),MAX_FEED_SIZE);
  const page=Math.max(Number(searchParams.get("page")||1)||1,1);
  const [profileRes,experiencesRes,jobsRes,recruiterJobsRes]=await Promise.all([
   supabase.from("Profile").select("targetRoles,targetCities,contractPreferences,remotePreference,preferredSectors").eq("userId",user.id).maybeSingle(),
   supabase.from("Experience").select("startDate").eq("userId",user.id),
   // Discovery visibility is intentionally independent from application readiness.
   // Users must be able to discover the market broadly; readiness is enforced when applying.
   supabase.from("Job").select("*").eq("isActive",true).order("createdAt",{ascending:false}),
   supabase.from("RecruiterJob").select("*").eq("status","published").eq("applicationReady",true).order("createdAt",{ascending:false})
  ]);
  if(profileRes.error)throw new Error(profileRes.error.message);if(experiencesRes.error)throw new Error(experiencesRes.error.message);if(jobsRes.error)throw new Error(jobsRes.error.message);if(recruiterJobsRes.error)throw new Error(recruiterJobsRes.error.message);
  const profile:Profile=profileRes.data||{targetRoles:[],targetCities:[],contractPreferences:[],remotePreference:"INDIFFERENT",preferredSectors:[]};const yearsExperience=computeYearsExperience((experiencesRes.data as Experience[])||[]);
  type Unified={source:"discovery"|"recruiter";sourceId:string;title:string;description:string;location:string|null;contractType:string|null;remoteMode:string|null;minExperienceYears:number|null;companyName:string|null;companyId:string|null;createdAt:string;publishedAt:string|null;deadline:string|null;sourceUrl:string|null;sourcePlatform:string|null;applicationProfile:Record<string,unknown>;visualUrl:string|null;visualSource:string|null;applicationCheckedAt:string|null;sector:string|null;tags:string[]};
  const discovery=((jobsRes.data as Job[])||[]).filter(j=>isFresh(j.sourcePublishedAt,j.deadline,j.createdAt));
  const recruiter=((recruiterJobsRes.data as RecruiterJobRow[])||[]).filter(j=>isFresh(null,null,j.createdAt));
  let unified:Unified[]=[...discovery.map(j=>({source:"discovery" as const,sourceId:j.id,title:j.title,description:j.description,location:j.location,contractType:j.contractType,remoteMode:j.remoteMode,minExperienceYears:j.minExperienceYears,companyName:null,companyId:j.companyId,createdAt:j.createdAt,publishedAt:j.sourcePublishedAt,deadline:j.deadline,sourceUrl:j.sourceUrl,sourcePlatform:j.source||null,applicationProfile:j.applicationProfile,visualUrl:j.visualUrl,visualSource:j.visualSource,applicationCheckedAt:j.applicationCheckedAt,sector:j.aiSector||null,tags:Array.isArray(j.aiSkills)?j.aiSkills as string[]:[]})),...recruiter.map(j=>({source:"recruiter" as const,sourceId:j.id,title:j.title,description:j.description,location:j.location,contractType:j.contract,remoteMode:j.remoteMode,minExperienceYears:j.minExperienceYears,companyName:j.companyName,companyId:null,createdAt:j.createdAt,publishedAt:j.createdAt,deadline:null,sourceUrl:j.sourceUrl,sourcePlatform:j.sourcePlatform||"JOBLY",applicationProfile:j.applicationProfile,visualUrl:j.visualUrl,visualSource:j.visualSource,applicationCheckedAt:j.applicationCheckedAt,sector:j.sector||null,tags:j.tags||[]}))];
  if(filterContract)unified=unified.filter(j=>normalize(j.contractType)===normalize(filterContract));if(filterCity)unified=unified.filter(j=>normalize(j.location).includes(normalize(filterCity)));if(filterRemote)unified=unified.filter(j=>normalize(j.remoteMode)===normalize(filterRemote));if(search){const n=normalize(search);unified=unified.filter(j=>normalize(j.title).includes(n)||normalize(j.companyName).includes(n));}
  const companyIds=Array.from(new Set(unified.map(j=>j.companyId).filter(Boolean))) as string[];const companiesRes=companyIds.length?await supabase.from("Company").select("id,name,logoUrl,description,website,verified").in("id",companyIds):{data:[] as Company[],error:null};if(companiesRes.error)throw new Error(companiesRes.error.message);const companiesById=new Map((companiesRes.data as Company[]).map(c=>[c.id,c]));
  const ranked=unified.map(job=>{const {matchPercent,breakdown}=computeMatch(profile,yearsExperience,job);const company=job.companyId?companiesById.get(job.companyId):undefined;const publishedAt=job.publishedAt||job.createdAt;const expirationAt=expirationFor(job.publishedAt,job.deadline,job.createdAt);const ageHours=Math.max(0,(Date.now()-new Date(publishedAt).getTime())/3600000);const freshness=Math.max(0,1-Math.min(ageHours/(MAX_OFFER_AGE_DAYS*24),1));const score=Math.round(matchPercent*.8+freshness*20);return{source:job.source,id:job.sourceId,title:job.title,description:job.description,location:job.location,contractType:job.contractType,remoteMode:job.remoteMode,minExperienceYears:job.minExperienceYears,createdAt:job.createdAt,publishedAt,expirationAt:expirationAt.toISOString(),deadline:job.deadline,sourceUrl:job.sourceUrl,sourcePlatform:job.sourcePlatform,applicationReady:job.source === "recruiter" ? true : false,applicationProfile:job.applicationProfile,applicationCheckedAt:job.applicationCheckedAt,visualUrl:job.visualUrl||company?.logoUrl||null,visualSource:job.visualSource||(company?.logoUrl?"COMPANY_LOGO":null),company:company?{id:company.id,name:company.name,logoUrl:company.logoUrl,description:company.description,website:company.website,verified:company.verified}:job.companyName?{id:null,name:job.companyName,logoUrl:null,description:null,website:null,verified:false}:null,matchPercent,matchBreakdown:breakdown,feedScore:score};}).sort((a,b)=>b.feedScore-a.feedScore||new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime());
  const totalAvailable=ranked.length;const start=(page-1)*limit;const results=ranked.slice(start,start+limit);const matchingCount=ranked.reduce((count,job)=>count+(job.matchPercent>=60?1:0),0);
  return NextResponse.json({totalAvailable,matchingCount,count:results.length,page,limit,hasMore:start+limit<totalAvailable,yearsExperience,jobs:results,freshnessPolicy:{dailyTarget:200,maxAgeDays:60,explicitDeadlineOverridesMaxAge:true,expirationField:"expirationAt",ordering:"match_then_freshness_then_publication",externalRequiresApplicationReady:true}});
 }catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Impossible de charger les offres."},{status:500});}
}
