drop table if exists public."JiaCEOMessage" cascade;
drop table if exists public."JiaCEOConversation" cascade;
drop table if exists public."JiaEnterpriseMemory" cascade;
create table public."JiaEnterpriseMemory" (id uuid primary key default gen_random_uuid(), domain text not null, title text not null, content text not null, source_type text not null default 'CANONICAL', source_ref text, sensitivity text not null default 'INTERNAL', version integer not null default 1, active boolean not null default true, "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now());
create index jia_enterprise_memory_domain_idx on public."JiaEnterpriseMemory"(domain, active);
create table public."JiaCEOConversation" (id uuid primary key default gen_random_uuid(), "adminUserId" text not null references public."User"(id) on delete cascade, title text, "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now());
create index jia_ceo_conversation_admin_idx on public."JiaCEOConversation"("adminUserId", "updatedAt" desc);
create table public."JiaCEOMessage" (id uuid primary key default gen_random_uuid(), "conversationId" uuid not null references public."JiaCEOConversation"(id) on delete cascade, role text not null check (role in ('user','assistant','system')), content text not null, metadata jsonb not null default '{}'::jsonb, "createdAt" timestamptz not null default now());
create index jia_ceo_message_conversation_idx on public."JiaCEOMessage"("conversationId", "createdAt");
alter table public."JiaEnterpriseMemory" enable row level security;
alter table public."JiaCEOConversation" enable row level security;
alter table public."JiaCEOMessage" enable row level security;
revoke all on public."JiaEnterpriseMemory", public."JiaCEOConversation", public."JiaCEOMessage" from anon, authenticated;
grant all on public."JiaEnterpriseMemory", public."JiaCEOConversation", public."JiaCEOMessage" to service_role;
create policy "JIA admins can read enterprise memory" on public."JiaEnterpriseMemory" for select to authenticated using (exists (select 1 from public."User" u where u."authUserId" = (select auth.uid())::text and u.role = 'ADMIN'));
create policy "JIA admins own CEO conversations" on public."JiaCEOConversation" for all to authenticated using (exists (select 1 from public."User" u where u.id = "adminUserId" and u."authUserId" = (select auth.uid())::text and u.role = 'ADMIN')) with check (exists (select 1 from public."User" u where u.id = "adminUserId" and u."authUserId" = (select auth.uid())::text and u.role = 'ADMIN'));
create policy "JIA admins own CEO messages" on public."JiaCEOMessage" for all to authenticated using (exists (select 1 from public."JiaCEOConversation" c join public."User" u on u.id = c."adminUserId" where c.id = "conversationId" and u."authUserId" = (select auth.uid())::text and u.role = 'ADMIN')) with check (exists (select 1 from public."JiaCEOConversation" c join public."User" u on u.id = c."adminUserId" where c.id = "conversationId" and u."authUserId" = (select auth.uid())::text and u.role = 'ADMIN'));
insert into public."JiaEnterpriseMemory"(domain,title,content,source_type,source_ref,sensitivity,version) values
('VISION','JOBLY — Vision 20/20','JOBLY n''est pas un job board. JOBLY est conçu comme un Career Operating System : un système d''exploitation de carrière qui accompagne une personne depuis son entrée sur le marché du travail jusqu''à sa progression, sa mobilité, son recrutement et son évolution professionnelle. Formule directrice : JOBLY ne cherche pas seulement un emploi pour toi. JOBLY construit, pilote et optimise ta trajectoire professionnelle.','CANONICAL','README.md#vision','INTERNAL',1),
('PRODUCT','JOBLY Intelligence','La vision structurante relie Talent Intelligence, Market Intelligence et Mobility Intelligence autour du Career Brain et du Career Twin. Les briques incluent Career GPS, Career Gap, Readiness, Learning Intelligence, Opportunity Intelligence, Mobility Intelligence, Apply Engine, Interview AI et Career Companion. Les piliers Bons Plans comprennent Jobly Campus, Community, Mobility et Events, qui communiquent conceptuellement avec J''IA.','CANONICAL','README.md#vision','INTERNAL',1),
('PRODUCT','Career Twin','Le Career Twin est la représentation dynamique de la trajectoire professionnelle d''un Talent. Il agrège identité, profil, expériences, compétences, formation, certifications, projets, objectifs, aspirations, préférences, mobilité, candidatures, entretiens, résultats et progression. Les informations doivent distinguer DECLARED, DOCUMENT, VERIFIED et INFERRED lorsque pertinent. J''IA ne doit jamais transformer une inférence en fait.','CANONICAL','README.md#career-twin','INTERNAL',1),
('PRODUCT','Campus','Jobly Campus cible les étudiants, car la carrière commence avant le premier emploi. Il peut couvrir stages académiques/professionnels/vacances, jobs étudiants/temps partiel, freelancing, préparation de concours, formation, bénévolat et premières expériences pratiques. Des programmes B2B peuvent être co-créés avec acteurs publics/privés, collectivités, églises et ONG.','CANONICAL','PROJECT_CONTEXT','INTERNAL',1),
('TECHNICAL','Architecture actuelle','Stack observée : Next.js App Router, React, TypeScript, Tailwind, Supabase, PostgreSQL, Prisma, PWA et APIs Next.js/route handlers. Le projet sépare le code Next.js des fonctions Supabase Edge. Le package indique notamment Next.js 15.1.3, React 19, TypeScript 5.8.2 et Prisma 6.16.3. Ne pas remplacer la stack sans justification technique explicite.','CANONICAL','README.md#stack','INTERNAL',1),
('TECHNICAL','J''IA — architecture existante','J''IA dispose déjà d''un contexte personnel canonical, d''une mémoire JiaMemory, d''événements JiaEvent, d''un gateway transverse et d''un ai-core Supabase Edge avec fallback déterministe et plusieurs providers. Les opérations existantes couvrent notamment offre, CV, matching, candidature, learning, interview, career companion et notifications. Le CEO Intelligence Core ajoute cockpit, KPI réels, alertes, projections, CEO Actions et CEOAuditLog.','CANONICAL','GITHUB:867aab9','INTERNAL',1),
('COMMERCIAL','Jobly Business Model','La vision commerciale de JOBLY couvre Talent, Recruiter, Partner et les services de mobilité/écosystème. Le produit doit optimiser la progression de carrière plutôt que le nombre d''actions. Côté Recruiter, la vision cible Need → Job Description → AI Recruiter → Talent Search → Explainable Matching → Shortlist → Interview → Hire → Onboarding → Retention. Recruit + Move ajoute Talent Fit, Mobility Fit, Cost of Hire et Retention Potential.','CANONICAL','README.md#recruiter','CONFIDENTIAL',1),
('COMMERCIAL','CEO Intelligence','J''IA CEO doit assister l''administrateur/fondateur dans la lecture, le pilotage et l''optimisation de JOBLY : CEO Intelligence, BI, Growth, Commercial, Finance, Market Intelligence, Operations et Customer Intelligence. Elle surveille acquisition, activation, rétention, conversion, revenus, coûts, marges, commissions, rentabilité, santé opérationnelle et signaux marché. Boucle : Observer → Comprendre → Prédire → Décider → Exécuter → Mesurer → Corriger → Apprendre.','CANONICAL','README.md#jia-ceo','CONFIDENTIAL',1),
('GOVERNANCE','Séparation des informations','Le CEO Core est séparé de l''intelligence exposée aux utilisateurs Talent/Recruiter/Partner. J''IA user-facing ne doit jamais divulguer finances, marges, objectifs, prévisions, stratégie, concurrence, KPI internes, commissions ou données permettant de les déduire. Le contrôle d''accès doit être technique, par rôle/permission, et audité.','CANONICAL','README.md#jia-ceo','CONFIDENTIAL',1),
('GOVERNANCE','Décisions et validation humaine','J''IA peut analyser, alerter, simuler, recommander et préparer une exécution. Les décisions juridiquement ou financièrement engageantes restent soumises à validation humaine explicite. Les projections ne sont pas des garanties et les diagnostics doivent être présentés comme incertains lorsque les données sont insuffisantes.','CANONICAL','README.md#jia-ceo','INTERNAL',1),
('ORGANIZATION','Organigramme fonctionnel connu','Le modèle de rôles JOBLY actuellement prévu comprend TALENT, RECRUITER, PARTNER, ADMIN, SUPPORT, FINANCE, MODERATOR et ANALYST. L''administrateur/fondateur dispose du périmètre CEO Intelligence. Aucun nom de personne ou rattachement hiérarchique non documenté ne doit être inventé par J''IA.','CANONICAL','README.md#database','CONFIDENTIAL',1),
('TECHNICAL','État de maturité','JOBLY distingue les notions CODÉ, TESTÉ, VALIDÉ et DÉPLOYÉ. Une route ou une brique présente dans le code n''est pas automatiquement une fonctionnalité validée. Les validations BUILD/E2E/runtime restent obligatoires avant de déclarer le produit production-ready.','CANONICAL','PROJECT_CONTEXT','INTERNAL',1);
