-- Jobly Recruitment 360° v2 — Lot 7 tables: secure report links and reviews
create table if not exists public."RecruitmentReportShare"(id uuid primary key default gen_random_uuid(),"recruitmentId" uuid not null references public."Recruitment360"(id) on delete cascade,"applicationId" uuid references public."Application"(id) on delete cascade,"tokenHash" text not null unique,scope text not null default 'RECRUITMENT_SUMMARY' check(scope in('RECRUITMENT_SUMMARY','APPLICATION_SUMMARY')),"expiresAt" timestamptz not null,"createdByUserId" text not null references public."User"(id) on delete restrict,"revokedAt" timestamptz,"lastAccessedAt" timestamptz,"accessCount" integer not null default 0 check("accessCount">=0),"createdAt" timestamptz not null default now());
create table if not exists public."RecruitmentReview"(id uuid primary key default gen_random_uuid(),"recruitmentId" uuid not null references public."Recruitment360"(id) on delete cascade,"applicationId" uuid not null references public."Application"(id) on delete cascade,"reviewerUserId" text not null references public."User"(id) on delete cascade,"reviewerRole" text not null check("reviewerRole" in('TALENT','RECRUITER')),"processRating" integer not null check("processRating" between 1 and 5),"experienceRating" integer not null check("experienceRating" between 1 and 5),"joblyRating" integer not null check("joblyRating" between 1 and 5),recommendation boolean,comment text check(comment is null or length(comment)<=2000),status text not null default 'PENDING' check(status in('PENDING','PUBLISHED','REJECTED')),"moderatedByUserId" text references public."User"(id) on delete set null,"moderatedAt" timestamptz,"createdAt" timestamptz not null default now(),"updatedAt" timestamptz not null default now(),unique("applicationId","reviewerUserId","reviewerRole"));
alter table public."RecruitmentReportShare" enable row level security;
alter table public."RecruitmentReview" enable row level security;
revoke all on public."RecruitmentReportShare",public."RecruitmentReview" from anon,authenticated;
grant select on public."RecruitmentReportShare",public."RecruitmentReview" to authenticated;
create policy "Lot7 shares recruiter members" on public."RecruitmentReportShare" for select to authenticated using(exists(select 1 from public."RecruitmentRole" rr where rr."recruitmentId"=public."RecruitmentReportShare"."recruitmentId" and rr."authUserId"=(select auth.uid())));
create policy "Lot7 reviews participant or recruiter" on public."RecruitmentReview" for select to authenticated using(exists(select 1 from public."RecruitmentRole" rr where rr."recruitmentId"=public."RecruitmentReview"."recruitmentId" and rr."authUserId"=(select auth.uid())) or exists(select 1 from public."Application" a join public."User" u on u.id::text=a."userId"::text where a.id=public."RecruitmentReview"."applicationId" and u."authUserId"=(select auth.uid())::text));
create index if not exists "RecruitmentReportShare_recruitmentId_expiresAt_idx" on public."RecruitmentReportShare"("recruitmentId","expiresAt");
create index if not exists "RecruitmentReportShare_applicationId_idx" on public."RecruitmentReportShare"("applicationId");
create index if not exists "RecruitmentReview_recruitmentId_status_idx" on public."RecruitmentReview"("recruitmentId",status);
create index if not exists "RecruitmentReview_applicationId_idx" on public."RecruitmentReview"("applicationId");
create index if not exists "RecruitmentReview_reviewerUserId_idx" on public."RecruitmentReview"("reviewerUserId");