"use client";
import { Suspense, useEffect, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { getSupabaseClient } from "@/lib/supabase";
import { jobPublicUrl } from "@/lib/site";
import PageHeader from "@/components/PageHeader";
import BottomNav from "@/components/BottomNav";
import TalentBackground from "@/components/TalentBackground";

type Job = Record<string, any>;
function JobDetailInner() {
  const router=useRouter(), params=useParams<{id:string}>(), search=useSearchParams(), source=search.get("source");
  const [job,setJob]=useState<Job|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!params.id||(source!=="discovery"&&source!=="recruiter")){setError("Lien d'offre invalide.");setLoading(false);return;} fetch(`/api/jobs/${encodeURIComponent(params.id)}?source=${encodeURIComponent(source)}`).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.message||"Offre introuvable.");return b.job}).then(setJob).catch(e=>setError(e instanceof Error?e.message:"Offre introuvable.")).finally(()=>setLoading(false));},[params.id,source]);
  async function apply(){if(busy)return;setBusy(true);try{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){sessionStorage.setItem("jobly:after-login", `/jobs/${params.id}?source=${source}`);router.push("/");return;}const r=await fetch("/api/applications",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${s.data.session.access_token}`},body:JSON.stringify({source,jobId:params.id})});const b=await r.json();if(r.status===409){alert("Tu as déjà postulé à cette offre.");return;}if(!r.ok)throw Error(b.message||"Impossible d'enregistrer la candidature.");alert("Candidature enregistrée. Tu peux la compléter dans Mes candidatures.");}catch(e){alert(e instanceof Error?e.message:"Erreur réseau.");}finally{setBusy(false)}}
  if(loading)return <main className="talent-shell grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">Chargement…</main>;
  if(error||!job)return <main className="talent-shell min-h-[100dvh] bg-[#F7FAFF] text-navy"><PageHeader label="Offre" onBack={()=>router.push("/jobs")} theme="talent"/><div className="mx-auto mt-8 max-w-2xl px-5"><div className="talent-card rounded-[24px] bg-white p-6 shadow-sm"><h1 className="text-xl font-black">Offre indisponible</h1><p className="mt-2 text-sm text-slate-500">{error||"Cette offre n'est plus disponible."}</p><button onClick={()=>router.push("/jobs")} className="mt-5 rounded-2xl bg-jobly-blue px-5 py-3 text-sm font-black text-white">Retour aux offres</button></div></div></main>;
  const company=job.company?.name||job.companyName||"Entreprise", contract=job.contractType||job.contract, remote=job.remoteMode==="YES"?"Télétravail":job.remoteMode==="PARTIAL"?"Hybride":job.remoteMode==="NO"?"Présentiel":null;
  const deadline=job.deadline?new Date(job.deadline).toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"}):null;
  const tags:string[]=Array.isArray(job.tags)?job.tags:[];
  return <main className="talent-shell relative min-h-[100dvh] bg-[#F7FAFF] pb-28 text-navy"><TalentBackground/><div className="relative z-10"><PageHeader label="Détail de l'offre" onBack={()=>router.push("/jobs")} theme="talent"/><div className="mx-auto max-w-3xl px-5 py-6"><section className="rounded-[28px] bg-white p-6 shadow-sm"><div className="flex items-start gap-4">{job.company?.logoUrl?<img src={job.company.logoUrl} alt={company} className="h-14 w-14 shrink-0 rounded-2xl object-cover"/>:<div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-blue-50 text-2xl">💼</div>}<div className="min-w-0"><h1 className="text-2xl font-black">{job.title}</h1><p className="mt-1 font-bold text-jobly-blue">{company}</p><p className="mt-2 text-xs text-slate-500">{[job.location,contract,remote].filter(Boolean).join(" · ")}</p></div></div>
    <div className="mt-5 flex flex-wrap gap-2">{job.minExperienceYears!=null&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{job.minExperienceYears} an{job.minExperienceYears>1?"s":""} min.</span>}{job.sector&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{job.sector}</span>}{deadline&&<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Candidatures jusqu'au {deadline}</span>}{tags.map((t)=><span key={t} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-jobly-blue">{t}</span>)}</div>
    {job.description&&<div className="mt-7"><h2 className="text-base font-black">Description</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{job.description}</p></div>}
    {(job.salary||job.salaryMin!=null)&&<p className="mt-5 text-sm font-bold">Rémunération : {job.salary||`${job.salaryMin??""}${job.salaryMax!=null?` – ${job.salaryMax}`:""} ${job.salaryCurrency||"XAF"}`}</p>}
    {job.company?.description&&<div className="mt-7 rounded-2xl bg-slate-50 p-4"><h2 className="text-sm font-black">À propos de {company}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{job.company.description}</p>{job.company?.website&&<a href={job.company.website.startsWith("http")?job.company.website:`https://${job.company.website}`} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-jobly-blue underline">Site de l'entreprise</a>}</div>}
    <button disabled={busy} onClick={apply} className="mt-7 w-full rounded-2xl bg-jobly-blue py-3.5 text-sm font-black text-white disabled:opacity-50">{busy?"Enregistrement…":"J'ai postulé"}</button><button onClick={()=>navigator.clipboard?.writeText(jobPublicUrl(params.id,source||undefined))} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white py-3 text-sm font-black">Copier le lien de l'offre</button></section></div></div><BottomNav active="/jobs"/></main>;
}
export default function JobDetailPage() {
  return <Suspense fallback={<main className="talent-shell grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">Chargement…</main>}><JobDetailInner/></Suspense>;
}
