"use client";
import { Suspense, useEffect, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { ExternalLink } from "lucide-react";
import { getSupabaseClient } from "@/lib/supabase";
import { jobPublicUrl } from "@/lib/site";
import PageHeader from "@/components/PageHeader";
import BottomNav from "@/components/BottomNav";
import TalentBackground from "@/components/TalentBackground";
import CompanyLogo from "@/components/CompanyLogo";
import { cleanCompanyName, cleanJobDescription } from "@/lib/jobContent";

type Job = Record<string, any>;
function GmailIcon({size=18}:{size?:number}) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none"><path d="M3 5.5A2.5 2.5 0 0 1 5.5 3h13A2.5 2.5 0 0 1 21 5.5v13A2.5 2.5 0 0 1 18.5 21H5.5A2.5 2.5 0 0 1 3 18.5v-13Z" fill="white"/><path d="M4.5 6.2 12 12l7.5-5.8V18a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1V6.2Z" fill="#EA4335"/><path d="M4.5 6.2 12 12l7.5-5.8-1.1-1.6L12 9.4 5.6 4.6 4.5 6.2Z" fill="#4285F4"/><path d="M4.5 6.2V18c0 .55.45 1 1 1h2V8.12L4.5 6.2Z" fill="#34A853"/><path d="M19.5 6.2V18c0 .55-.45 1-1 1h-2V8.12l3-1.92Z" fill="#FBBC04"/></svg>; }
function WhatsAppIcon({size=18}:{size?:number}) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" fill="#25D366"/><path d="M8.7 7.6c.3-.3.7-.3 1 0l1.2 1.4c.25.3.25.7.02 1l-.55.72c.5 1 1.35 1.85 2.35 2.35l.72-.55c.3-.23.7-.23 1 .02l1.4 1.2c.3.25.3.7 0 1-.65.75-1.6 1.2-2.65 1.05-1.65-.23-3.4-1.3-4.8-2.7s-2.47-3.15-2.7-4.8c-.15-1.05.3-2 1.05-2.65Z" fill="white"/></svg>; }
function JobDetailInner() {
  const router=useRouter(), params=useParams<{id:string}>(), search=useSearchParams(), source=search.get("source");
  const [job,setJob]=useState<Job|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!params.id||(source!=="discovery"&&source!=="recruiter")){setError("Lien d'offre invalide.");setLoading(false);return;} fetch(`/api/jobs/${encodeURIComponent(params.id)}?source=${encodeURIComponent(source)}`).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.message||"Offre introuvable.");return b.job}).then(setJob).catch(e=>setError(e instanceof Error?e.message:"Offre introuvable.")).finally(()=>setLoading(false));},[params.id,source]);
  function whatsappPhone(profile:any){const values=Array.isArray(profile?.phoneNumbers)?profile.phoneNumbers:typeof profile?.phone==="string"?[profile.phone]:[];const raw=values.find((v:any)=>/237|^6|^2/.test(String(v)))||values[0];if(!raw)return null;let digits=String(raw).replace(/[^0-9]/g,"");if(digits.startsWith("237"))return digits;if(digits.startsWith("6")&&digits.length===9)return "237"+digits;if(digits.startsWith("2")&&digits.length===9)return "237"+digits;return null;}
  async function openWhatsApp(){const phone=whatsappPhone(job?.applicationProfile);if(!phone)return;try{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){sessionStorage.setItem("jobly:after-login", "/jobs/"+params.id+"?source="+source);router.push("/");return;}const r=await fetch("/api/cv-share",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+s.data.session.access_token},body:JSON.stringify({source,jobId:params.id})});const b=await r.json();if(!r.ok)throw Error(b.message||"Impossible de préparer le CV.");const cvUrl=window.location.origin+"/cv/share/"+b.token;const message="Bonjour, je suis "+b.candidateName+". Je souhaite vous soumettre ma candidature au poste de "+(job?.title||"ce poste")+(company?" chez "+company:"")+".\n\n📄 CV "+b.candidateName+" — Candidature "+(company||job?.title||"ce poste")+"\n"+cvUrl;window.open("https://wa.me/"+phone+"?text="+encodeURIComponent(message),"_blank","noopener,noreferrer");}catch(e){alert(e instanceof Error?e.message:"Impossible d'ouvrir WhatsApp.");}}
  function openEmail(){if(!emailChannel)return;const email=String(job?.applicationProfile?.applicationEmail||job?.applicationProfile?.email||"").trim();if(!email)return;const subject=encodeURIComponent(`Candidature — ${job?.title||"Offre Jobly"}`);const body=encodeURIComponent(`Bonjour,\n\nJe souhaite vous soumettre ma candidature au poste de ${job?.title||"ce poste"}.\n\nVous trouverez mon profil et mon CV via Jobly : ${window.location.origin}/jobs/${params.id}?source=${source}\n\nCordialement.`);window.open(`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(email)}&su=${subject}&body=${body}`,"_blank","noopener,noreferrer");} async function apply(){if(phoneChannel){await openWhatsApp();return;}if(applicationLink){window.open(applicationLink,"_blank","noopener,noreferrer");return;}if(emailChannel){openEmail();}}
  if(loading)return <main className="talent-shell grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">Chargement…</main>;
  if(error||!job)return <main className="talent-shell min-h-[100dvh] bg-[#F7FAFF] text-navy"><PageHeader label="Offre" onBack={()=>router.replace("/jobs")} theme="talent"/><div className="mx-auto mt-8 max-w-2xl px-5"><div className="talent-card rounded-[24px] bg-white p-6 shadow-sm"><h1 className="text-xl font-black">Offre indisponible</h1><p className="mt-2 text-sm text-slate-500">{error||"Cette offre n'est plus disponible."}</p><button onClick={()=>router.replace("/jobs")} className="mt-5 rounded-2xl bg-jobly-blue px-5 py-3 text-sm font-black text-white">Retour aux offres</button></div></div></main>;
  const company=cleanCompanyName(job.company?.name||job.companyName), emailChannel=Boolean(job.applicationProfile?.applicationEmail||job.applicationProfile?.email), phoneChannel=Boolean(job.applicationProfile?.applicationPhone||job.applicationProfile?.phone||job.applicationProfile?.phoneNumbers?.length), applicationLink=String(job.applicationProfile?.applicationUrl||job.applicationProfile?.applyUrl||job.applicationProfile?.url||"").trim(), contract=job.contractType||job.contract, remote=job.remoteMode==="YES"?"Télétravail":job.remoteMode==="PARTIAL"?"Hybride":job.remoteMode==="NO"?"Présentiel":null;
  const deadline=job.deadline?new Date(job.deadline).toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"}):null;
  const tags:string[]=Array.isArray(job.tags)?job.tags:[];
  const cleanDescription=cleanOfferDescription(job.description);
  return <main className="talent-shell relative min-h-[100dvh] bg-[#F7FAFF] pb-28 text-navy"><TalentBackground/><div className="relative z-10"><PageHeader label="Détail de l'offre" onBack={()=>router.replace("/jobs")} theme="talent"/><div className="mx-auto max-w-3xl px-5 py-6"><section className="rounded-[28px] bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><CompanyLogo companyName={company} logoUrl={job.company?.logoUrl} domain={job.company?.domain} website={job.company?.website} size={56} /><div className="min-w-0"><h1 className="text-2xl font-black">{job.title}</h1><p className="mt-1 font-bold text-jobly-blue">{company}</p><p className="mt-2 text-xs text-slate-500">{[job.location,contract,remote].filter(Boolean).join(" · ")}</p></div></div>
    <div className="mt-5 flex flex-wrap gap-2">{job.minExperienceYears!=null&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{job.minExperienceYears} an{job.minExperienceYears>1?"s":""} min.</span>}{job.sector&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{job.sector}</span>}{deadline&&<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Candidatures jusqu'au {deadline}</span>}{tags.map((t)=><span key={t} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-jobly-blue">{t}</span>)}</div>
    {(emailChannel||phoneChannel)&&<div className="mt-5 flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4">{emailChannel?<GmailIcon size={24}/>:<WhatsAppIcon size={24}/>}<div><p className="text-sm font-black text-slate-900">Canal de candidature détecté</p><p className="mt-1 text-sm text-slate-600">{emailChannel?"Adresse mail":"Téléphone / WhatsApp"}</p></div></div>}{cleanDescription&&<div className="mt-7 rounded-2xl border border-slate-100 bg-white p-1"><h2 className="px-3 pt-3 text-lg font-black text-[#0057B8]">Description du poste</h2><div className="mt-3 space-y-5 px-3 pb-3 text-sm leading-7 text-slate-600">{cleanDescription.split(/\n\s*\n/).map((paragraph:string,index:number)=>{const lines=paragraph.split("\n").map(x=>x.trim()).filter(Boolean);const first=lines[0]||"";const heading=/^(description|missions?|responsabilités?|compétences?|profil|qualifications?|exigences?|conditions?|avantages?|formation|expérience|poste|candidature|pour postuler)\s*[:：-]?$/i.test(first);const body=heading?lines.slice(1):lines;return <section key={index}>{heading&&<h3 className="mb-2 text-lg font-black text-[#00A6A6]">{first.replace(/[:：-]+$/,"")}</h3>}{body.map((line:string,lineIndex:number)=>{const bullet=/^[•*-]\s*/.test(line);return <p key={lineIndex} className={bullet?"pl-5 -indent-5":""}>{bullet?"• ":""}{bullet?line.replace(/^[•*-]\s*/,""):line}</p>})}</section>})}</div></div>}
    {(job.salary||job.salaryMin!=null)&&<p className="mt-5 text-sm font-bold">Rémunération : {job.salary||`${job.salaryMin??""}${job.salaryMax!=null?` – ${job.salaryMax}`:""} ${job.salaryCurrency||"XAF"}`}</p>}
    {job.company?.description&&<div className="mt-7 rounded-2xl bg-slate-50 p-4"><h2 className="text-sm font-black">À propos de {company}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{job.company.description}</p>{job.company?.website&&<a href={job.company.website.startsWith("http")?job.company.website:`https://${job.company.website}`} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-jobly-blue underline">Site de l'entreprise</a>}</div>}
    {applicationLink && <a href={applicationLink} target="_blank" rel="noreferrer" className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl border border-jobly-blue bg-white py-3.5 text-sm font-black text-jobly-blue"><ExternalLink size={17}/>Voir la plateforme de candidature</a>}
    <button type="button" onClick={() => router.push("/cv?mode=adapt&jobId=" + encodeURIComponent(params.id) + "&source=" + encodeURIComponent(source || ""))} className="mt-3 w-full rounded-2xl border border-[#FFE135] bg-[#FFFBE0] py-3.5 text-sm font-black text-[#2E3F4F]">Adapter votre CV pour cette candidature</button>
    <button disabled={busy} onClick={apply} className="mt-2 flex w-full items-center justify-center gap-2 rounded-2xl bg-jobly-blue py-3.5 text-sm font-black text-white disabled:opacity-50">
      {emailChannel ? <><GmailIcon size={18}/><span>Postuler</span></> : phoneChannel ? <><WhatsAppIcon size={18}/><span>Postuler</span></> : applicationLink ? <><ExternalLink size={17}/><span>Postuler</span></> : <span>Postuler</span>}
    </button>
    <button onClick={() => navigator.clipboard?.writeText(jobPublicUrl(params.id, source || undefined))} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white py-3 text-sm font-black">Copier le lien de l'offre</button>
    </section></div></div><BottomNav active="/jobs"/></main>;
}
export default function JobDetailPage() {
  return <Suspense fallback={<main className="talent-shell grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">Chargement…</main>}><JobDetailInner/></Suspense>;
}
