import { NextRequest, NextResponse } from "next/server";
import { adminClient, ensureUser, getAuthUser } from "../../../lib/server-auth";
function n(v:any){return String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
export async function GET(req:NextRequest){
 try{const auth=await getAuthUser(req);if(!auth)return NextResponse.json({message:"Session requise."},{status:401});const sb=adminClient();const u=await ensureUser(sb,auth);
 const [p,e,j]=await Promise.all([sb.from("Profile").select("targetRoles,targetCities,contractPreferences,remotePreference,preferredSectors").eq("userId",u.id).maybeSingle(),sb.from("Experience").select("startDate").eq("userId",u.id),sb.from("Job").select("id,title,description,location,contractType,remoteMode,minExperienceYears,companyId,isActive").eq("isActive",true).limit(1000)]);for(const r of[p,e,j])if(r.error)throw new Error(r.error.message);
 type ProfileRow={targetRoles?:unknown[]|null;targetCities?:unknown[]|null;contractPreferences?:unknown[]|null;remotePreference?:unknown|null;preferredSectors?:unknown[]|null};
 const profile:ProfileRow=(p.data??{}) as ProfileRow;const ex=e.data||[];const years=ex.length?Math.floor((Date.now()-Math.min(...ex.map((x:any)=>new Date(x.startDate).getTime())))/(365.25*86400000)):0;const roles=(profile.targetRoles??[]).map(n);const cities=(profile.targetCities??[]).map(n);const contracts=(profile.contractPreferences??[]).map(n);const remote=n(profile.remotePreference)||"indifferent";
 const rows=(j.data||[]).map((x:any)=>{const role=roles.length&&roles.some((r:string)=>n(x.title).includes(r))?1:0;const city=cities.length&&cities.includes(n(x.location))?1:0;const contract=contracts.length&&contracts.includes(n(x.contractType))?1:0;let rm=0;if(remote==="indifferent"||remote===n(x.remoteMode))rm=1;else if(remote==="yes"&&n(x.remoteMode)==="partial")rm=.5;const exp=years>=(x.minExperienceYears||0)?1:0;const base=(role+city+contract+rm+exp)/5*100;const completeness=[x.title,x.location,x.contractType,x.description].filter(Boolean).length/4*100;const score=Math.round(base*.7+completeness*.15+(x.description?.length>200?15:5));return {...x,opportunityScore:Math.min(100,score),matchPercent:Math.round(base),breakdown:{role,city,contract,remote:rm,experience:exp},why:[role?"Métier cible correspondant":null,city?"Ville souhaitée":null,contract?"Contrat souhaité":null,rm?"Télétravail compatible":null,exp?"Expérience suffisante":null].filter(Boolean)}}).sort((a:any,b:any)=>b.opportunityScore-a.opportunityScore);
 return NextResponse.json({count:rows.length,opportunities:rows.slice(0,50)});
 }catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Opportunités indisponibles."},{status:500});}}
export async function POST(req:NextRequest){try{const auth=await getAuthUser(req);if(!auth)return NextResponse.json({message:"Session requise."},{status:401});const sb=adminClient();const u=await ensureUser(sb,auth);const b=await req.json();if(!b.jobId||!['INTERESTED','NOT_RELEVANT','APPLIED'].includes(b.feedback))return NextResponse.json({message:"Feedback invalide."},{status:400});const {error}=await sb.from("AuditLog").insert({userId:u.id,action:`OPPORTUNITY_FEEDBACK_${b.feedback}`,entityType:"Job",entityId:b.jobId,metadata:{source:b.source||"discovery"}});if(error)throw new Error(error.message);return NextResponse.json({ok:true});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Feedback impossible."},{status:500});}}
