"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation"; import {getSupabaseClient} from "@/lib/supabase";
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(Math.round(n||0))+" XAF";
export default function JiaCEO(){const router=useRouter();const [snapshot,setSnapshot]=useState<any>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){router.replace("/");return;}const r=await fetch("/api/admin/jia/ceo",{headers:{Authorization:"Bearer "+s.data.session.access_token}}),b=await r.json();if(!r.ok){setError(b.message||"Accès refusé.");setLoading(false);return;}setSnapshot(b.snapshot);setLoading(false)})().catch(()=>{setError("Impossible de charger le cockpit CEO.");setLoading(false)})},[router]);
 if(loading)return <main className="grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">J’IA construit la situation…</main>;
 if(error)return <main className="min-h-[100dvh] bg-[#F7FAFF] p-6 text-navy"><button onClick={()=>router.back()} className="mb-6 text-sm font-bold">← Retour</button><h1 className="text-2xl font-black">CEO Intelligence</h1><p className="mt-3 text-red-600">{error}</p></main>;
 const k=snapshot.kpis; return <main className="min-h-[100dvh] bg-[#F7FAFF] text-navy"><div className="mx-auto max-w-6xl px-5 py-6">
 <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">J’IA · CEO Intelligence</p><h1 className="mt-1 text-3xl font-black">Cockpit de pilotage</h1><p className="mt-1 text-sm text-slate-500">Observer → Comprendre → Prédire → Décider → Mesurer</p></div><button onClick={()=>router.push("/admin")} className="rounded-xl bg-white px-4 py-2 text-sm font-bold shadow-sm">Administration</button></div>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Offres actives",k.activeJobs],["Nouveaux talents · 7j",k.newUsers7d],["Candidatures · 7j",k.applications7d],["Revenus · 30j",money(k.revenue30d)]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-500">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</section>
 <section className="mt-5 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-black">Situation business</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><p>Recruiter Jobs publiés <b>{k.publishedRecruiterJobs}</b></p><p>Abonnements actifs <b>{k.activeSubscriptions}</b></p><p>Valeur récurrente mensuelle <b>{money(k.recurringMonthlyValue)}</b></p><p>Commissions à traiter <b>{money(k.commissionsOutstanding)}</b></p><p>Partners <b>{k.partners}</b></p><p>J’IA · succès 7j <b>{k.aiSuccessRate}%</b></p></div></div>
 <div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Projection 30 jours</h2><div className="mt-4 space-y-3 text-sm"><p>Revenus <b className="float-right">{money(snapshot.projections.revenue30d)}</b></p><p>Candidatures <b className="float-right">{snapshot.projections.applications30d}</b></p><p>Nouveaux utilisateurs <b className="float-right">{snapshot.projections.newUsers30d}</b></p></div><p className="mt-4 text-xs text-slate-500">Extrapolation du rythme 7 jours.</p></div></section>
 <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Alertes</h2>{snapshot.alerts.length?<div className="mt-3 space-y-3">{snapshot.alerts.map((a:any)=><div key={a.id} className="rounded-xl border p-3"><b>{a.severity} · {a.title}</b><p className="mt-1 text-sm text-slate-600">{a.detail}</p></div>)}</div>:<p className="mt-3 text-sm text-slate-500">Aucune alerte selon les seuils actuels.</p>}</div>
 <div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">CEO Actions</h2>{snapshot.actions.length?<div className="mt-3 space-y-3">{snapshot.actions.map((a:any)=><div key={a.id} className="rounded-xl border p-3"><b>{a.priority} · {a.title}</b><p className="mt-1 text-sm text-slate-600">{a.reason}</p></div>)}</div>:<p className="mt-3 text-sm text-slate-500">Aucune action prioritaire déclenchée.</p>}</div></section>
 <p className="mt-5 text-xs text-slate-400">Dernière observation : {new Date(snapshot.generatedAt).toLocaleString("fr-FR")}. Les décisions engageantes restent sous validation humaine.</p>
 </div></main>}
