"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation"; import {getSupabaseClient} from "@/lib/supabase";
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(Math.round(n||0))+" XAF";
export default function JiaCEO(){const router=useRouter();const [snapshot,setSnapshot]=useState<any>(null),[layers,setLayers]=useState<any[]>([]),[marketWatch,setMarketWatch]=useState<any[]>([]),[watchLoading,setWatchLoading]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=await getSupabaseClient().auth.getSession();if(!s.data.session){router.replace("/");return;}const r=await fetch("/api/admin/jia/ceo",{headers:{Authorization:"Bearer "+s.data.session.access_token}}),b=await r.json();if(!r.ok){setError(b.message||"Accès refusé.");setLoading(false);return;}setSnapshot(b.snapshot); const ir=await fetch("/api/admin/jia/intelligence",{headers:{Authorization:"Bearer "+s.data.session.access_token}}); const ib=await ir.json(); if(ir.ok)setLayers(Array.isArray(ib.layers)?ib.layers:[]); setLoading(false)})().catch(()=>{setError("Impossible de charger le cockpit CEO.");setLoading(false)})},[router]);
 if(loading)return <main className="grid min-h-[100dvh] place-items-center bg-[#F7FAFF] font-bold text-navy">J’IA construit la situation…</main>;
 if(error)return <main className="min-h-[100dvh] bg-[#F7FAFF] p-6 text-navy"><button onClick={()=>router.back()} className="mb-6 text-sm font-bold">← Retour</button><h1 className="text-2xl font-black">CEO Intelligence</h1><p className="mt-3 text-red-600">{error}</p></main>;
 const k=snapshot.kpis; return <main className="min-h-[100dvh] bg-[#F7FAFF] text-navy"><div className="mx-auto max-w-6xl px-5 py-6">
 <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">J’IA · CEO Intelligence</p><h1 className="mt-1 text-3xl font-black">Cockpit de pilotage</h1><p className="mt-1 text-sm text-slate-500">Observer → Comprendre → Prédire → Décider → Mesurer</p></div><div className="flex gap-2"><button onClick={async()=>{setWatchLoading(true);try{const s=await getSupabaseClient().auth.getSession();if(!s.data.session)return;const r=await fetch("/api/admin/jia/intelligence?includeMarketWatch=true",{headers:{Authorization:"Bearer "+s.data.session.access_token}});const b=await r.json();if(r.ok)setMarketWatch(Array.isArray(b.marketWatch)?b.marketWatch:[]);}finally{setWatchLoading(false);}}} className="rounded-xl bg-canari-yellow px-4 py-2 text-sm font-black">{watchLoading?"Veille…":"Actualiser Market Watch"}</button><button onClick={()=>router.push("/admin")} className="rounded-xl bg-white px-4 py-2 text-sm font-bold shadow-sm">Administration</button></div></div>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Offres actives",k.activeJobs],["Nouveaux talents · 7j",k.newUsers7d],["Candidatures · 7j",k.applications7d],["Revenus · 30j",money(k.revenue30d)]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-500">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</section>
 <section className="mt-5 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-black">Situation business</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><p>Recruiter Jobs publiés <b>{k.publishedRecruiterJobs}</b></p><p>Abonnements actifs <b>{k.activeSubscriptions}</b></p><p>Valeur récurrente mensuelle <b>{money(k.recurringMonthlyValue)}</b></p><p>Commissions à traiter <b>{money(k.commissionsOutstanding)}</b></p><p>Partners <b>{k.partners}</b></p><p>J’IA · succès 7j <b>{k.aiSuccessRate}%</b></p></div></div>
 <div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Prévisions 7 / 30 / 90 jours</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3">{[["7j",snapshot.projections.horizons?.d7],["30j",snapshot.projections.horizons?.d30],["90j",snapshot.projections.horizons?.d90]].map(([label,v]:any)=><div key={label} className="rounded-xl bg-slate-50 p-3"><b>{label}</b><p>Revenus {money(v?.revenue)}</p><p>Candidatures {v?.applications ?? 0}</p><p>Nouveaux {v?.newUsers ?? 0}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Projections mécaniques à partir du rythme observé; elles ne constituent pas des garanties.</p></div></section>
 <section className="mt-5 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-black">Intelligences transversales</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{layers.map((l:any)=><div key={l.layer} className="rounded-xl border p-3"><div className="flex items-center justify-between"><b>{l.layer}</b><span className="text-[10px] font-black uppercase text-slate-500">{l.confidence}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{l.summary}</p></div>)}</div></div><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Risques & opportunités</h2><div className="mt-3 space-y-2 text-sm">{(snapshot.risks||[]).slice(0,4).map((r:any)=><p key={r.id}><b>{r.severity}</b> · {r.title}</p>)}{(snapshot.opportunities||[]).slice(0,4).map((o:any)=><p key={o.id}>↗ {o.title}</p>)}</div></div></section>
<section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Market Watch vérifié</h2><span className="text-xs text-slate-500">{marketWatch.length} requêtes</span></div>{marketWatch.length?<div className="mt-4 grid gap-3 md:grid-cols-3">{marketWatch.map((w:any)=><div key={w.query} className="rounded-xl border p-3"><div className="flex items-center justify-between"><b className="text-sm">{w.status}</b><span className="text-xs text-slate-500">{Math.round((w.confidence||0)*100)}%</span></div><p className="mt-1 text-xs text-slate-500">{w.query}</p><p className="mt-2 text-sm">{w.facts?.[0]||w.limitations?.[0]||"Aucun signal exploitable."}</p><p className="mt-2 text-[11px] text-slate-400">{w.contradictions?.length||0} contradiction(s) · {w.sources?.length||0} source(s)</p></div>)}</div>:<p className="mt-3 text-sm text-slate-500">Aucune veille Web chargée. La recherche reste explicite pour limiter les coûts et préserver le contrôle.</p>}</section>\n<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Alertes</h2>{snapshot.alerts.length?<div className="mt-3 space-y-3">{snapshot.alerts.map((a:any)=><div key={a.id} className="rounded-xl border p-3"><b>{a.severity} · {a.title}</b><p className="mt-1 text-sm text-slate-600">{a.detail}</p></div>)}</div>:<p className="mt-3 text-sm text-slate-500">Aucune alerte selon les seuils actuels.</p>}</div>
 <div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">CEO Actions</h2>{snapshot.actions.length?<div className="mt-3 space-y-3">{snapshot.actions.map((a:any)=><div key={a.id} className="rounded-xl border p-3"><b>{a.priority} · {a.title}</b><p className="mt-1 text-sm text-slate-600">{a.reason}</p></div>)}</div>:<p className="mt-3 text-sm text-slate-500">Aucune action prioritaire déclenchée.</p>}</div></section>
 <p className="mt-5 text-xs text-slate-400">Dernière observation : {new Date(snapshot.generatedAt).toLocaleString("fr-FR")}. Les décisions engageantes restent sous validation humaine.</p>
 </div></main>}
