"use client";
import {useEffect,useState} from "react";
import AppShell from "@/components/ui/AppShell";
import {Button,Card,EmptyState,ErrorState,LoadingState,PageIntro,Section} from "@/components/ui";
export default function Applications360(){const[apps,setApps]=useState<any[]>([]),[state,setState]=useState("loading"),[error,setError]=useState("");
async function load(){try{setState("loading");const r=await fetch("/api/recruitment360/applications");const d=await r.json();if(!r.ok)throw new Error(d.message);setApps(d.applications??[]);setState("ready")}catch(e){setError(e instanceof Error?e.message:"Erreur");setState("error")}}
useEffect(()=>{void load()},[]);
async function action(b:any){setError("");const r=await fetch("/api/recruitment360/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});const d=await r.json();if(!r.ok){setError(d.message);return}await load()}
return <AppShell role="recruiter" active="/recruiter/applications360" title="Candidatures 360°" eyebrow="RECRUTEMENT 360°" initial="R" width="lg"><PageIntro eyebrow="LOT 3" title="Candidatures & sélection" subtitle="ATS, critères, justificatifs, vivier et décisions de présélection." actions={<Button href="/recruiter">Tableau de bord</Button>}/>{state==="loading"&&<LoadingState/>}{state==="error"&&<ErrorState title={error} onRetry={load}/>} {state==="ready"&&(apps.length?<div className="space-y-3">{apps.map(a=><Card key={a.id}><div className="flex flex-col gap-3"><div><h2 className="font-black">{a.userId}</h2><p className="text-sm text-muted">{a.status} · ATS {a.assessment?.atsScore??"—"} · Complétude {a.assessment?.profileCompleteness??"—"}%</p><p className="text-sm">{a.letterText||"Lettre non renseignée."}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>void action({action:"score",applicationId:a.id})}>Recalculer ATS</Button><Button size="sm" onClick={()=>void action({action:"shortlist",applicationId:a.id,status:"SHORTLISTED"})}>Retenir</Button><Button size="sm" variant="ghost" onClick={()=>void action({action:"shortlist",applicationId:a.id,status:"RESERVE"})}>Vivier</Button><Button size="sm" variant="ghost" onClick={()=>void action({action:"shortlist",applicationId:a.id,status:"DEFERRED",deferUntil:new Date(Date.now()+7*86400000).toISOString()})}>Différer 7 j</Button><Button size="sm" variant="ghost" onClick={()=>{const reason=prompt("Motif du refus (5 caractères min.)")||"";if(reason)void action({action:"shortlist",applicationId:a.id,status:"REJECTED",reason})}}>Refuser</Button></div></div></Card>)} </div>:<EmptyState title="Aucune candidature à traiter"/>)}</AppShell>}
