import type { JIA100Move } from "./movements";

export type ClipConfig = { webm:string; mp4?:string; duration:number; fit:{left:number;top:number;width:number;scaleFrom:number;scaleTo:number;originY:number;} };
const FIT={left:0,top:0,width:100,scaleFrom:1.015,scaleTo:1,originY:50} as const;
const duration=5.334;
function cfg(name:string,d=duration):ClipConfig{return {webm:`/jia/clips/${name}.webm`,mp4:`/jia/clips/${name}.mp4`,duration:d,fit:{...FIT}};}
const CLIPS={welcome:cfg("welcome"),validate:cfg("validate"),reassure:cfg("reassure"),encourage:cfg("encourage"),analyze:cfg("analyze"),curious:cfg("curious"),presentChart:cfg("present-chart"),filter:cfg("filter"),point:cfg("point",2.134),apply:cfg("apply"),callHr:cfg("call-hr"),handshake:cfg("handshake"),presentTeam:cfg("present-team"),payOs:cfg("pay-os"),secure:cfg("secure"),disappointed:cfg("disappointed"),tired:cfg("tired"),surprised:cfg("surprised"),celebrate:cfg("celebrate"),proud:cfg("proud"),wink:cfg("wink"),write:cfg("write")} satisfies Record<string,ClipConfig>;
export const JIA_CLIPS:Partial<Record<JIA100Move,ClipConfig>>={wave_hi:CLIPS.welcome,stamping:CLIPS.validate,scarf_touch:CLIPS.reassure,clap:CLIPS.encourage,scanning:CLIPS.analyze,look_around:CLIPS.curious,chart_up:CLIPS.presentChart,point_button:CLIPS.filter,point_bubble:CLIPS.filter,point_score:CLIPS.point,point_cv:CLIPS.apply,point_left:CLIPS.point,point_right:CLIPS.point,point_up:CLIPS.point,point_down:CLIPS.point,point_self:CLIPS.point,point_you:CLIPS.callHr,hand_shake:CLIPS.handshake,explain_wide:CLIPS.presentTeam,money:CLIPS.payOs,hand_chest:CLIPS.secure,think_doubt:CLIPS.disappointed,breathe_deep:CLIPS.tired,eyebrow_raise:CLIPS.surprised,celebrate_jump:CLIPS.celebrate,celebrate_fist:CLIPS.celebrate,proud:CLIPS.proud,wink_left:CLIPS.wink,wink_right:CLIPS.wink,writing:CLIPS.write,reading:CLIPS.apply,checking:CLIPS.validate,matching:CLIPS.presentChart,searching:CLIPS.curious,target:CLIPS.point,rocket:CLIPS.celebrate};
export const CLIP_COOLDOWN_MS=3000;
export function pickClipSources(cfg:ClipConfig){const sources=[{src:cfg.webm,type:'video/webm; codecs="vp9"'}];if(cfg.mp4)sources.push({src:cfg.mp4,type:"video/mp4"});return sources;}
let preloaded=false;
export function preloadClips(){if(preloaded||typeof window==="undefined")return;preloaded=true;const cfg=JIA_CLIPS.wave_hi;if(!cfg)return;const run=()=>{const v=document.createElement("video");v.preload="metadata";v.muted=true;v.src=cfg.webm;};const idle=(window as any).requestIdleCallback as undefined|((cb:()=>void,o?:{timeout:number})=>void);if(idle)idle(run,{timeout:4000});else window.setTimeout(run,2500);}
