"use client";
import { useEffect,useState } from "react";
import { Lock, UserRound, Sparkles } from "lucide-react";
import { useParams,useRouter } from "next/navigation";

export default function PublicRecruiterDiscovery(){
 const {token}=useParams<{token:string}>();const router=useRouter();const [data,setData]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/recruiter/discover/"+encodeURIComponent(token)).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message||"Indisponible");return b}).then(setData).catch(e=>setError(e.message));},[token]);
 if(error)return <main className="min-h-[100dvh] grid place-items-center bg-[#F5F7FA] p-6"><div className="rounded-3xl bg-white p-8 text-center shadow-xl"><h1 className="font-black">Expérience indisponible</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></main>;
 if(!data)return <main className="min-h-[100dvh] grid place-items-center bg-[#F5F7FA] font-black text-[#0B2447]">Analyse des talents…</main>;
 return <main className="min-h-[100dvh] bg-[#F5F7FA] text-[#0B2447]">
  <header className="border-b bg-white px-4 py-3"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="font-black"><span className="text-[#174EA6]">JOB</span><span className="text-[#FFE135]">LY</span></div><button onClick={()=>router.push("/recruiter/onboarding")} className="rounded-full bg-[#174EA6] px-4 py-2 text-xs font-black text-white">Créer mon compte recruteur</button></div></header>
  <div className="mx-auto max-w-6xl px-4 py-8"><div className="mb-7"><p className="text-[10px] font-black uppercase tracking-[.25em] text-slate-400">JOBLY · TALENT INTELLIGENCE</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Les talents correspondant à votre besoin</h1><p className="mt-2 text-sm text-slate-500">{data.share?.jobTitle||data.job?.title||"Votre opportunité"} {data.share?.companyName?"· "+data.share.companyName:""} — classement indicatif basé sur les informations publiques des Talents.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(data.talents||[]).map((t:any)=><article key={t.id} className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-blue-50 font-black text-[#174EA6]">{t.profilePhotoUrl?<img src={t.profilePhotoUrl} alt="" className="h-full w-full object-cover"/>:<UserRound size={20}/>}</div><div className="min-w-0"><h2 className="truncate font-black">{t.name}</h2><p className="truncate text-xs text-slate-500">{t.headline}</p></div></div><div className="mt-5 flex items-end justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Correspondance</div><div className="text-3xl font-black text-[#174EA6]">{t.matchPercent}%</div></div><div className="text-right text-xs text-slate-500">{t.experienceYears} an{t.experienceYears>1?"s":""}<br/>{t.location}</div></div><div className="mt-4 flex flex-wrap gap-1.5">{t.skills.map((s:string)=><span key={s} className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{s}</span>)}</div><button onClick={()=>router.push("/")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 py-3 text-xs font-black"><Lock size={13}/> Voir le profil complet</button></article>)}</div>
  {(!data.talents||!data.talents.length)&&<div className="rounded-3xl bg-white p-10 text-center shadow-sm"><Sparkles className="mx-auto text-[#FFE135]"/><h2 className="mt-3 font-black">Votre marché Talent est prêt à s'ouvrir.</h2><p className="mt-2 text-sm text-slate-500">Les profils apparaissent lorsqu'ils ont activé leur visibilité publique.</p></div>}
  <div className="mt-8 rounded-[28px] bg-[#081B36] p-6 text-white sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#FFE135]">Pourquoi Jobly ?</p><h2 className="mt-2 text-2xl font-black">Ne cherchez plus seulement des CV. Trouvez les talents qui correspondent à votre besoin.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">Créez votre compte recruteur pour accéder aux profils complets, contacter les talents et construire votre shortlist.</p><button onClick={()=>router.push("/")} className="mt-5 rounded-2xl bg-[#FFE135] px-5 py-3 text-sm font-black text-[#081B36]">Créer mon compte gratuitement</button></div>
  </div>
 </main>
}
